tenacitas: tenacitas::program::options_t< use > Struct Template Reference
tenacitas::program::options_t< use > Struct Template Reference
Class to parse program options.
#include <program.h>
Public Types
typedef std::string name
name of an option
typedef std::string value
value of an option
Public Member Functions
void parse (int p_argc, char **p_argv, std::initializer_list< name > &&p_mandatory={})
parse parses the options passed to a program
std::optional< bool > get_bool_param (const name &p_name) const
Retrieves the bool parameter, if possible.
std::optional< value > get_single_param (const name &p_name) const
Retrieves a single parameter, if possible.
std::optional< std::list< value > > get_set_param (const name &p_name) const
Retrieves the values of a parameter.
Friends
std::ostream & operator<< (std::ostream &p_out, const options_t &p_options)
Output operator.
Detailed Description
template<bool use = true>
struct tenacitas::program::options_t< use >
Class to parse program options.
Template Parameters
use makes tenacitas::tester::test to be compiled only if actually used
Examples
options_000/main.cpp.
Definition at line 57 of file program.h.
Member Function Documentation
get_bool_param()
template<bool use = true> std::optional<bool> tenacitas::program::options_t< use >::get_bool_param (const name & p_name) const inline
Retrieves the bool parameter, if possible.
Parameters
p_name is the name of the parameter
Returns
{true} if it was possible to retrieve, and p_name exists; {} otherwise
Examples
options_000/main.cpp.
Definition at line 135 of file program.h.
{
         booleans::const_iterator _ite =
             std::find(m_booleans.begin(), m_booleans.end(), p_name);
         if (_ite == m_booleans.end()) {
             return {};
         }
         return {true};
     }
Referenced by tenacitas::tester::test< use >::test().
get_set_param()
template<bool use = true> std::optional<std::list<value> > tenacitas::program::options_t< use >::get_set_param (const name & p_name) const inline
Retrieves the values of a parameter.
Parameters
p_name is the name of the parameter
Returns
{list with the values} if p_name was found; {} if not
Examples
options_000/main.cpp.
Definition at line 167 of file program.h.
{
         sets::const_iterator _ite = std::find_if(
             m_sets.begin(), m_sets.end(),
             [p_name](const std::pair<name, values> &p_set) -> bool {
                 return p_set.first == p_name;
             });
         if (_ite == m_sets.end()) {
             return {};
         }
         return {_ite->second};
     }
Referenced by tenacitas::tester::test< use >::test().
get_single_param()
template<bool use = true> std::optional<value> tenacitas::program::options_t< use >::get_single_param (const name & p_name) const inline
Retrieves a single parameter, if possible.
Parameters
p_name is the name of the parameter
Returns
{<some-value>} if p_name was found; {} if not
Examples
options_000/main.cpp.
Definition at line 150 of file program.h.
{
         singles::const_iterator _ite = std::find_if(
             m_singles.begin(), m_singles.end(),
             [p_name](const std::pair<name, value> &p_single) -> bool {
                 return p_single.first == p_name;
             });
         if (_ite == m_singles.end()) {
             return {};
         }
         return {_ite->second};
     }
parse()
template<bool use = true> void tenacitas::program::options_t< use >::parse (int p_argc, char ** p_argv, std::initializer_list< name > && p_mandatory = {}) inline
parse parses the options passed to a program
Parameters
p_argc number of options
p_argv vector of strings with the options
p_mandatory set of options that are mandatory
an option must be preceded with '–', like '–file-name abc.txt'.
There are 3 types of parameter: boolean, where the parameter has no value, like '–print-log'
single, where the parameter has a single value, like '–file-name abc.txt'
set, where the paramter has a set of values, like '–tests { test1 test2 test3 }
Exceptions
std::runtime_error
Examples
options_000/main.cpp.
Definition at line 83 of file program.h.
                                                          {}) {
         int _last = p_argc - 1;
         int _i = 1;
         while (_i <= _last) {
             if (!is_option(p_argv[_i])) {
                 throw std::runtime_error("parameter '" +
                                          std::string(p_argv[_i]) +
                                          "' should be an option");
             }
             name _name(std::string(&(p_argv[_i][2]),
                                    &(p_argv[_i][strlen(p_argv[_i])])));
             if (_i == _last) {
                 m_booleans.insert(std::move(_name));
                 break;
             }
             ++_i;
             if (is_option(p_argv[_i])) {
                 m_booleans.insert(std::move(_name));
             } else {
                 if (p_argv[_i][0] == '{') {
                     _i = parse_set(std::move(_name), _last, p_argv, _i);
                 } else {
                     std::string _str(&p_argv[_i][0],
                                      &p_argv[_i][strlen(p_argv[_i])]);
                     m_singles.insert({std::move(_name), std::move(_str)});
                     ++_i;
                 }
             }
         }
         for (const name &_name : p_mandatory) {
             if ((!get_bool_param(_name)) && (!get_single_param(_name)) &&
                 (!get_set_param(_name))) {
                 throw std::runtime_error(
                     "parameter '" + _name +
                     "' should have been defined, but it was not");
             }
         }
     }
Referenced by tenacitas::tester::test< use >::test().
The documentation for this struct was generated from the following file:
program.h