@startuml

hide footbox



caller -> device : call(switchboard)
device -> switchboard : connect()
collections handlers
switchboard -> handlers : get()
handlers --> switchboard : handler 
switchboard --> device : connection(handler)
device --> caller : connected
caller -> device : start_conversation()
device -> handler : start_conversation()
handler -> device : conversation
caller -> device : send(message)
device -> handler : send(conversation, message)
handler -> device : send(conversation, message)
caller -> device : end_conversation()
device -> handler : end_conversation(conversation)
handler -> device : conversation_ended
@enduml