@startuml

hide empty members
allow_mixing

namespace entities {

enum types_of_ending {
never
at
number
}

enum  types_of_repetition 
{
  micro
  milli
  second
  minute
  hour
  day
  week
  month
  year
}


class ending_t<types_of_ending>
class ending_never
class ending_at
class ending_number

class repetition_t<types_of_repetition>
class repetition_day
class repetition_week
class repetition_month
class repetition_year

class  recurrency_t<types_of_repetition, types_of_ending>

ending_never ..> "<<binds>>" ending_t
ending_at ..>  "<<binds>>" ending_t
ending_number ..>  "<<binds>>" ending_t

repetition_day  .up.>  "<<binds>>" repetition_t
repetition_week .up.>  "<<binds>>" repetition_t
repetition_month .up.>  "<<binds>>" repetition_t
repetition_year .up.>  "<<binds>>" repetition_t


ending_t -[hidden]-> repetition_t 

}

@enduml