@startuml

hide empty members
allow_mixing
' left to right direction


namespace  sql {

namespace entities {
class Size
class Type
class Name
class Column  {
	isNull : boolean
	isUnique : boolean
	isAutoincrement : boolean
}

class Table  {
	name: Name
}

class PrimaryKey 

class ForeignKey  {
	name: Name
}

class Database {
	name : Name
}
class Ip
class Host {
	name : Name
}
class Server {
	name : Name
}

class InsertsDefinitions 

class InsertDefinition {
	amountOfRows : uint16_t
}

enum ValuePattern {
	userInput
	random
	algorithmGenerated
	autoIncrement
	nullValue
	inferiorLimit
	superiorLimit 
}

enum ForeignKeyMatchPattern {
	userChoice
	random
	onePerOne
	oneForAll
}

class TableValues
class ColumnHeader

TableValues *-- "*"  ColumnHeader
ColumnHeader o-- Column
ColumnHeader *-- "*" Value

InsertDefinition *-- TableValues

Table  *-- "0..*" Column
Table  *-- "0..1" PrimaryKey 
Table  *-- "0..*" ForeignKey 
Table o-- Database

PrimaryKey   o-- Table 
PrimaryKey  o-- "1..*" Column 
PrimaryKey  o-- "0..*" ForeignKey 

Column  *-- Type
Column  +-- Type
Column  *-- Size
Column  *-- Name

ForeignKey  o-- Column

Database *-- "*" Table
Host *-- "*" Server
Host *-- Ip
Server *-- "*" Database

Database o-- Server

Server o-- Host

Hosts *-- "*" Host

InsertsDefinitions *-- "*" InsertDefinition
}

namespace business {
class InsertGenerator

InsertGenerator o-- sql.entities.InsertsDefinitions
InsertGenerator o-- sql.entities.Hosts
}
}


@enduml