@startuml

hide empty members
allow_mixing

namespace  sql {

namespace entities {
class Size
class Type
class Name
class Column {
	isNull : boolean
	isAutoIncrement : boolean
}
class PrimaryKey
class ForeignKey {
	name : Name
}
class Table {
	name : Name
}
class Database {
	name : Name
}
class Ip
class Host
class Server {
	name : Name
}

Column *-- Name
Column *-- Type
Column *-- Size

PrimaryKey o-- "*" Column
PrimaryKey o-- Table
ForeignKey o-- PrimaryKey

Table *-- PrimaryKey
Table *--  "*" ForeignKey
Table *-- "*" Column 
Table o-- Database
Database *-- "*" Table
Host *-- "*" Server
Server *-- "*" Database
Host *-- Ip
Column +-- Type
Database o-- Server
Server o-- Host
Hosts *-- "*" Host
}

namespace business {

}
}


@enduml