	@startuml

hide empty members
allow_mixing

namespace  sql {

namespace entities {
class Size
class Type
class Name
class Column {
	isNull : boolean
	isAutoIncrement : boolean
}
class PrimaryKey
class ForeignKey {
	name : Name
}
class Table {
	name : Name
}
class Database {
	name : Name
}
class Ip
class Host {
	name : Name
}
class Server {
	name : Name
}

class InsertDefinition {
	amountOfRows : uint16_t
}

class PrimaryKeyValue {
	value : string
}


class ColumnValue {
	
}

enum ColumnValuePattern {
	userInput
	random
	algorithmGenerated
	autoIncrement
	nullValue
}


class ForeignKeyValue {
	
}

enum ForeignKeyValuePattern {
	v1
	v2
}


Column *-- Name
Column *-- Type
Column *-- Size

PrimaryKey o-- "*" Column
PrimaryKey o-- Table
ForeignKey o-- PrimaryKey

Table *-- PrimaryKey
Table *--  "*" ForeignKey
Table *-- "*" Column 
Table o-- Database
Database *-- "*" Table
Host *-- "*" Server
Server *-- "*" Database
Host *-- Ip
Column +-- Type
Database o-- Server
Server o-- Host
Hosts *-- "*" Host
ColumnValue *-- ColumnValuePattern
ColumnValue +-- ColumnValuePattern
ColumnValue o-- Column
InsertDefinition *-- "nonPkCols *" ColumnValue
InsertDefinition *-- "0..*" PrimaryKeyValue
InsertDefinition o-- Table
PrimaryKeyValue *-- ColumnValue
ForeignKeyValue o-- ForeignKey
ForeignKeyValue +- ForeignKeyValuePattern
ForeignKeyValue *-- ForeignKeyValuePattern
InsertDefinition *-- "0..*" ForeignKeyValue
}

namespace business {
class InsertGenerator

InsertGenerator o--  "*" sql.entities.InsertDefinition
InsertGenerator o-- sql.entities.Hosts
}


}


@enduml