@startuml

set namespaceSeparator ::

hide empty members
allow_mixing
'left to right direction
skinparam linetype ortho

namespace  sql {

namespace entities {

class Size
enum Type {
	INT_1
	INT_2
	INT_4
	INT_8
	CHAR
	FIX_SIZE_CHAR
	VAR_SIZE_CHAR
	BLOB
	SMALL_REAL
	LONG_REAL
}
class Name


class Column


class AttributeColumn  {
	isNull : boolean
	isUnique : boolean
}

class PrimaryKey

class PrimaryKeyColumn  {
	isAutoIncrement : boolean
	isUnique : boolean
}

class ForeignKeyColumn  {
	name : Name
	isUnique : boolean
}

class Table  {
	name: Name
}


class ForeignKey  {
	name: Name
}

class Database {
	name : Name
}

class Ip

class Host {
	name : Name
}

class Server {
	name : Name
}

class InsertDefinition {
	amountOfRows : uint16_t
}
class InsertsDefinitions 

enum ValuePattern {
	userInput
	random
	algorithmGenerated
	autoIncrement
	nullValue
	inferiorLimit
	superiorLimit 
	userChoice
	random
	onePerOne
	oneForAll
}



class ColumnHeader

class TestDefinition
class TestsDefinitions

TestsDefinitions *-- "*" TestDefinition

Column *-- Type
Column +-- Type
Column *-- Size
Column *-- Name

TestDefinition *-- InsertsDefinitions

Column <|-- AttributeColumn
Column <|-- PrimaryKeyColumn 
Column <|-- ForeignKeyColumn 

Table  *--o "0..*" AttributeColumn
Table  *--o "0..1" PrimaryKey 
Table  *--o "0..*" ForeignKey

PrimaryKey *--o "0..*" PrimaryKeyColumn 
PrimaryKey o-- "0..*" ForeignKeyColumn

ForeignKey  *--o "1..*" ForeignKeyColumn 

ForeignKeyColumn o--  PrimaryKeyColumn 


Database *--o "*" Table
Host *--o "*" Server
Host *-- Ip

 
Server *--o "*" Database

Hosts *--o "*" Host

InsertsDefinitions *-- "*" InsertDefinition

'InsertDefinition *-- "*" ColumnHeader
InsertDefinition o-- Table

AttributeColumnHeader *-- AttributeValuePattern
AttributeColumnHeader o-- AttributeColumn

PrimaryKeyColumnHeader *-- PrimaryKeyValuePattern
PrimaryKeyColumnHeader o-- PrimaryKeyColumn

ForeignKeyColumnHeader *-- ForeignKeyValuePattern
ForeignKeyColumnHeader o-- ForeignKeyColumn

ColumnHeader *--o  "*" ColumnValue

ColumnHeader <|-- AttributeColumnHeader
ColumnHeader <|-- PrimaryKeyColumnHeader
ColumnHeader <|-- ForeignKeyColumnHeader

'ColumnValue *-- "0..1" SingleValuePattern

'InsertDefinition *-- "0..1" PrimaryKeyColumnHeader
'InsertDefinition *-- "0..*" AttributeColumnHeader
'InsertDefinition *-- "0..*" ForeignKeyColumnHeader

InsertDefinition *--"*" ColumnHeader

'AttributeColumnHeader ..> "<<local>>" RandomValueGenerator
}

namespace business {
class InsertsGenerators
class InsertGenerator
class RandomValueGenerator
class InsertGenerator {
	{abstract} + generate(entities::InsertsDefinitions,
		            entities::InsertDefinition)
}


InsertsGenerators o-- sql::entities::InsertsDefinitions
InsertsGenerators o-- sql::entities::Hosts

InsertsGenerators *-- "*" InsertGenerator

InsertGenerator ..> "<<local>>"  RandomValueGenerator
InsertGenerator ..> "<<param>>" sql::entities::InsertDefinition
InsertGenerator ..> "<<param>>" sql::entities::InsertsDefinitions

RandomValueGenerator o-- sql::entities::Column
}

}
@enduml