@startuml

set namespaceSeparator ::

hide empty members
allow_mixing
left to right direction
skinparam linetype ortho


namespace  sql {

namespace entities {

class Size
enum Type {
	INT_1
	INT_2
	INT_4
	INT_8
	CHAR
	FIX_SIZE_CHAR
	VAR_SIZE_CHAR
	BLOB
	SMALL_REAL
	LONG_REAL
	DATE
	DATE_TIME
}
class Name


class Column

enum Usage {
	attribute
	primaryKey
	foreignKey
}

class PrimaryKeyColumn
class ForeignKeyColumn
class AttributeColumn

class Table {
	name : Name
}

class Database
class Server
class Host
class Hosts

class PrimaryKey
class ForeignKey


class ValueGenerator

'class AttributeValueGenerator
 

class InsertsDefinitions

class InsertDefinition {
	amountOfRows : uint16_t
}

class Value {
	userInput : bool
	value: string
}

class ColumnValues

class ValuesGenerators

ValuesGenerators *-- "*" ValueGenerator

Hosts *-- "*" Host
Host *--o "*" Server
Server *--o "*" Database
Database *--o "*" Table

ColumnValues o-- ValueGenerator
ColumnValues o-- Column
ColumnValues *-- "*" Value

ValueGenerator *-- "*" Usage

InsertsDefinitions *-- "*" InsertDefinition

InsertDefinition o-- Table
InsertDefinition *-- "*" ColumnValues

PrimaryKey *--o "*" PrimaryKeyColumn
ForeignKey *--o "*" ForeignKeyColumn
PrimaryKey o--o "*" ForeignKeyColumn

Table *--o PrimaryKey
Table *--o "*" ForeignKey
Table *--o "*" AttributeColumn

Column *-- Usage
Column +-- Usage

Column *-- Type
Column +-- Type
Column *-- Size
Column *-- Name

Column <|-- PrimaryKeyColumn
Column <|-- ForeignKeyColumn
Column <|-- AttributeColumn

ForeignKeyColumn o-- PrimaryKeyColumn

}

namespace business {

class InsertsGenerators
class InsertGenerator

InsertsGenerators *-- "*" InsertGenerator

InsertsGenerators o-- sql::entities::InsertsDefinitions
InsertsGenerators  o-- sql::entities::Hosts
InsertGenerator ..> sql::entities::InsertsDefinitions
InsertGenerator ..> sql::entities::InsertDefinition
InsertGenerator ..> sql::entities::Hosts
}
}

@enduml