@startuml

hide empty members
allow_mixing
' left to right direction

namespace  sql {

namespace entities {
class Size
class Type
class Name

class AttributeColumn  {
	isNull : boolean
	isUnique : boolean
}

class PrimaryKeyColumn  {
	isAutoIncrement : boolean
	isUnique : boolean
}

class ForeignKeyColumn  {
	isUnique : boolean
}

class Table  {
	name: Name
}

class PrimaryKey 

class ForeignKey  {
	name: Name
}

class Database {
	name : Name
}
class Ip
class Host {
	name : Name
}
class Server {
	name : Name
}

class InsertsDefinitions 

class InsertDefinition {
	amountOfRows : uint16_t
}
class AttributeColumnInsertDefinition
class ForeignKeyColumnInsertDefinition
class PrimaryKeyColumnInsertDefinition

enum AttributeValuePattern {
	userInput
	random
	algorithmGenerated
	autoIncrement
	nullValue
	inferiorLimit
	superiorLimit 
}

enum PrimaryKeyValuePattern {
	userInput
	random
	algorithmGenerated
	autoIncrement	 
}

enum ForeignKeyMatchPattern {
	userChoice
	random
	onePerOne
	oneForAll
}

class TableValues
class ColumnHeader
class TestDefinition


TestDefinition *-- InsertsDefinitions

TableValues *-- "*"  ColumnHeader

Table  *-- "0..*" AttributeColumn 
Table  *-- "0..1" PrimaryKey 
Table  *-- "0..*" ForeignKey 
Table o-- Database

AttributeColumn o-- Table

PrimaryKey   o-- Table 
PrimaryKey  *-- "1..*" PrimaryKeyColumn 
PrimaryKey  *-- "0..*" ForeignKey 

PrimaryKeyColumn o-- PrimaryKey

'Column  *-- Type
'Column  +-- Type
'Column  *-- Size
'Column  *-- Name

ForeignKey  *-- "1..*" ForeignKeyColumn 
ForeignKey  o-- "*" PrimaryKeyColumn 
ForeignKey o-- Table

ForeignKeyColumn o-- ForeignKey

Database *-- "*" Table
Host *-- "*" Server
Host *-- Ip
Server *-- "*" Database

Database o-- Server

Server o-- Host

Hosts *-- "*" Host

InsertsDefinitions *-- "*" InsertDefinition

InsertDefinition *-- TableValues

ColumnHeader *--  "*" Value
ColumnHeader o-- "0..1" ForeignKeyColumn
ColumnHeader o-- "0..1" PrimaryKeyColumn
ColumnHeader o-- "0..1" AttributeColumn

AttributeColumnInsertDefinition *-- AttributeValuePattern
PrimaryKeyColumnInsertDefinition *-- PrimaryKeyValuePattern
ForeignKeyColumnInsertDefinition *-- ForeignKeyMatchPattern

AttributeColumnInsertDefinition o-- AttributeColumn 
ForeignKeyColumnInsertDefinition o-- ForeignKeyColumn
PrimaryKeyColumnInsertDefinition o-- PrimaryKeyColumn

InsertDefinition *-- AttributeColumnInsertDefinition
InsertDefinition *-- ForeignKeyColumnInsertDefinition
InsertDefinition *-- PrimaryKeyColumnInsertDefinition



namespace business {
class InsertGenerator

InsertGenerator o-- sql.entities.InsertsDefinitions
InsertGenerator o-- sql.entities.Hosts
}
}


@enduml