@startuml

hide empty members
allow_mixing

namespace  sql {

namespace entities {
class Size
class Type
class Name
class Column {
	isNull : boolean
	isAutoIncrement : boolean
}
class Columns 
class PrimaryKey
class PrimaryKeys
class ForeignKey {
	name : Name
}
class ForeignersKeys
class Table {
	name : Name
}
class Tables
class Database {
	name : Name
}
class Databases
class Ip
class Host
class Server {
	name : Name
}
Class Servers

Column *-- Name
Column *-- Type
Column *-- Size

Columns *-- "*" Column
Tables *-- "*" Table
PrimaryKey *-- "*" PrimaryKey
ForeignersKeys *-- "*" ForeignKey
Databases *-- "*" Database
Servers *-- "*" Server

Server o-- "*" Database 


PrimaryKey o-- "*" Column
PrimaryKey o-- Table
ForeignKey o-- PrimaryKey

Table *-- PrimaryKey
Table *--  "*" ForeignKey
Table *-- "*" Column 
Table o-- Database
Database *-- "*" Table
Host *-- "*" Server
Server *-- "*" Database
Host *-- Ip
Column +-- Type
}

namespace business {

}
}


@enduml