@startuml
hide methods

namespace crosswords {
	namespace entities {
		coordinate +-u- coord_x
		coordinate +-u- coord_y
		class word {
			dir : direction
		 	ori : orientation
		 	entry: lexeme
			answer :   lexeme
			des :  description
		}
		word +-u- word_size
		word *-r- "*" coordinate
		words *-- "*" word
		words +-- words_iterator
	}

	namespace business {
		class words_positioner {
			+ add(word)
   			+ operator()(crosswords.entities.coord_x, crosswords.entities.coord_y) : crosswords.entities.words
		}
		class positions_occupied {
			m_map : map<crosswords.entities.coordinate, char> 
		}
		word_positioner *-u- positions_occupied
		words_references *-- "*" crosswords.entities.words_iterator
		word_positioner .l.> words_references : <<parameter>>
		word_positioner ..>crosswords.entities.words_iterator : <<parameter>>
		words_positioner *-d- "current" words_references
		words_positioner *-- "* failures" words_references 

	}
}
@enduml