@startuml
hide attribute

namespace crosswords {

	namespace entities {

		enum direction {
			vertical
			horizontal
		}

		enum orientation {
			forward
			backward
		}

		coordinate +-- coord_x
		coordinate +-- coord_y

		word *-- direction
		word *-- orientation
		word *-- "entry" lexeme
		word *-- "*" coordinate
		word *-- "answer" lexeme
		word *-- description
		word +-- word_size

		words *-- "*" word
		words +-- words_iterator
	}

	namespace business {
		positioner *-- "*" crosswords.entities.words_iterator

		words_by_size *-- crosswords.entities.word_size

		words_by_size *-- "begin" words_iterators
		words_by_size *-- "end" words_iterators

		positioner *-- "*" words_by_size
		positioner *-- crosswords.entities.words

		class position_word {
		- position_word(all : crosswords.entities.words_iterator[], 
			to_position : crosswords.entities.words_iterator) : bool
		- is_valid(all : words_iterators, to_position : words_iterators_iterator) : bool
		}

		class positioner {
		+ add(word)
   		+ operator()(crosswords.entities.coord_x
			, crosswords.entities.coord_y) : crosswords.entities.words
		}

		words_by_size ..> position_word : <<local>>
		class words_by_size {
		+ position(words_iterators): bool
		}
		words_by_size *-- "attempts" crosswords.entities.words_iterator


	}
}
@enduml