@startuml

package std {

class list<T>
class shared_ptr<T>
class string
class pair<F,S>
class future<T>
package chrono {
        class milliseconds
}

}

package network {

enum interface_status {
     loaded
     loading
     unloading
     unloaded     
     opened
     opening
     closing
     closed
}

enum transmission_status {
     ok
     error_sending
     error_receiving
     error_interface_closed     
     error_interface_closing
     error_interface_opening
     error_interface_loading
     error_interface_unloading
     error_interface_unloaded
}    

enum interface_type {
     gprs
     wifi
     eth
     usb
     serial
}

enum signal_strength {
     UNKNOWN
     LEVEL_0
     LEVEL_1
     LEVEL_2
     LEVEL_3
     LEVEL_4
     LEVEL_5
     LEVEL_6
     LEVEL_7
     LEVEL_8
     LEVEL_9
}

enum choose_interface_algorithm {
     fastest
     most_stable
     algo_3
     algo_4
}

class manager <<singleton>> {
      + manager(choose_interface_algorithm)
      + get_interface(interface_type) : interface
      + get_interface() : interface
}

class interface {
      +load() : interface_status
      +open() : interface_status
      +close() : interface_status
      +unload() : interface_status
      +quality():signal_strength
      +send(const std::string &) : transmission_status
      +receive() : std::pair<transmission_status, std::string>
      +get_type() : interface_type
      +get_statud() : interface_status
}

package internal {
        class interfaces {
              +get_interface(interface_type) : interface
        }
}

manager *-- interfaces
manager *-- "m_choose_algorithm" choose_interface_algorithm
manager o-- "m_current" interface 

interfaces *-- "*" interface
interface *-- "m_interface_type" interface_type
interface *-- "m_interface_status" interface_status
interface *-- "m_transmission_status" transmission_status

}

package communication {

}

@enduml
