@startuml

package std {

class list<T>
class shared_ptr<T>
class string
class pair<F,S>
class future<T>
package chrono {
        class milliseconds
}

}

package network {

enum interface_status {
     loaded
     loading
     unloading
     unloaded     
     opened
     opening
     closing
     closed
}

enum transmission_status {
     ok
     error_sending
     error_receiving
     error_interface_closed     
     error_interface_closing
     error_interface_opening
     error_interface_loading
     error_interface_unloading
     error_interface_unloaded
}    

enum interface_type {
     mbb
     wifi
     eth
     ussd
     usb
     serial
}

enum signal_strength {
     0
     1
     2
     3
     4
     5
     6
     7
     8
     9
}
     
class interface {
+load() : interface_status
+open() : interface_status
+close() : interface_status
+unload() : interface_status
+quality():signal_strength
+send(const std::string &) : transmission_status
+receive() : std::pair<transmission_status, std::string>
+get_type() : interface_type
+get_statud() : interface_status
}

class interfaces {
+get_interface(interface_type) : interface
}

interfaces *-- "*" interface
interface *-- interface_type
interface *-- interface_status
interface *-- transmission_status

}

@enduml