@startuml

hide empty members

package layer {
    enum datalink {
        ethernet
        gprs
        wifi
    }
    enum  network {
        ipv4
        ipv6
    }
    enum transport {
        tcp
        udp
    }
    enum application {
        web_server
        mamba
    }

    application --> transport
    transport --> network
    network --> datalink
}    
class buffer
class connection {
    + read() : buffer
    + write(buffer)
}
note top of connection : equivalent to socket in BSD 

connection ..> "uses" transport
network ..> "determines" address
connection ..> "uses" network
@enduml