@startuml
hide empty members
async ..> async
async ..> calendar
async ..> container
async ..> log
async ..> number
async ..> traits
container ..> number
conversions ..> conversions
crosswords ..> async
crosswords ..> container
crosswords ..> crosswords
crosswords ..> log
crosswords ..> math
crosswords ..> number
log ..> log
log ..> number
log ..> traits
number ..> number
test ..> program
traits ..> traits
@enduml
