tenacitas: tenacitas::calendar::now< use > Struct Template Reference
tenacitas::calendar::now< use > Struct Template Reference
Calculates 'now' in different time units.
#include <calendar.h>
Static Public Member Functions
template<typename t_int = uint64_t>
static t_int microsecs ()
'now' in microseconds
static std::string iso8601_microsecs ()
'now' as a string in the sformat YYYY-MM-DD HH::MM::SS,999999
static std::string iso8601_microsecs (uint64_t p_microsecs)
A specific time as a string in the format 'YYYY-MM-DD HH::MM::SS,999999'.
template<typename t_int = uint64_t>
static t_int millisecs ()
'now' in milliseconds
static std::string iso8601_millisecs ()
'now' as a string in the format 'YYYY-MM-DD HH::MM::SS,999'
template<typename t_int = uint64_t>
static t_int secs ()
'now' in seconds
static std::string iso8601_secs ()
'now' as a string in the format 'YYYY-MM-DD HH::MM::SS'
template<typename t_int = uint64_t>
static t_int minutes ()
'now' in minutes
template<typename t_int = uint64_t>
static t_int hours ()
'now' in hours
template<typename t_int = uint64_t>
static t_int days ()
'now' in days
template<typename t_int = uint64_t>
static t_int months ()
'now' in months
template<typename t_int = uint64_t>
static t_int years ()
'now' in years
Detailed Description
template<bool use = true>
struct tenacitas::calendar::now< use >
Calculates 'now' in different time units.
Template Parameters
use exists to make log to be compiled only it is really used
Definition at line 39 of file calendar.h.
Member Function Documentation
days()
template<bool use = true> template<typename t_int = uint64_t> static t_int tenacitas::calendar::now< use >::days () inline static
'now' in days
Definition at line 152 of file calendar.h.
{
         return static_cast<t_int>(
             std::chrono::duration_cast<std::chrono::hours>(
                 std::chrono::system_clock::now().time_since_epoch())
                 .count() /
             24);
     }
Referenced by tenacitas::calendar::now< use >::months().
hours()
template<bool use = true> template<typename t_int = uint64_t> static t_int tenacitas::calendar::now< use >::hours () inline static
'now' in hours
Definition at line 142 of file calendar.h.
{
         return static_cast<t_int>(
             std::chrono::duration_cast<std::chrono::hours>(
                 std::chrono::system_clock::now().time_since_epoch())
                 .count());
     }
iso8601_microsecs() [1/2]
template<bool use = true> static std::string tenacitas::calendar::now< use >::iso8601_microsecs () inline static
'now' as a string in the sformat YYYY-MM-DD HH::MM::SS,999999
Definition at line 51 of file calendar.h.
{
         using namespace std;
         using namespace chrono;
         const auto _microsecs = microsecs();
         const time_t _time_t = static_cast<time_t>(_microsecs / 1000000);
         const auto _remainder = _microsecs % 1000000;
         stringstream _stream;
         _stream << put_time(std::localtime(&_time_t), "%Y-%m-%d %H:%M:%S,")
                 << std::setw(6) << std::setfill('0') << std::left << _remainder;
         return _stream.str();
     }
References tenacitas::calendar::now< use >::microsecs().
iso8601_microsecs() [2/2]
template<bool use = true> static std::string tenacitas::calendar::now< use >::iso8601_microsecs (uint64_t p_microsecs) inline static
A specific time as a string in the format 'YYYY-MM-DD HH::MM::SS,999999'.
Parameters
p_microsecs is the time one wants to convert to string
Definition at line 69 of file calendar.h.
{
         using namespace std;
         using namespace chrono;
         const time_t _time_t = static_cast<time_t>(p_microsecs / 1000000);
         const auto _remainder = p_microsecs % 1000000;
         stringstream _stream;
         _stream << put_time(std::localtime(&_time_t), "%Y-%m-%d %H:%M:%S,")
                 << std::setw(6) << std::setfill('0') << std::left << _remainder;
         return _stream.str();
     }
iso8601_millisecs()
template<bool use = true> static std::string tenacitas::calendar::now< use >::iso8601_millisecs () inline static
'now' as a string in the format 'YYYY-MM-DD HH::MM::SS,999'
Definition at line 93 of file calendar.h.
{
         using namespace std;
         using namespace chrono;
         const auto _microsecs = millisecs();
         const time_t _time_t = static_cast<time_t>(_microsecs / 1000);
         const auto _remainder = _microsecs % 1000;
         stringstream _stream;
         _stream << put_time(std::localtime(&_time_t), "%Y-%m-%d %H:%M:%S,")
                 << std::setw(3) << std::setfill('0') << std::left << _remainder;
         return _stream.str();
     }
References tenacitas::calendar::now< use >::millisecs().
iso8601_secs()
template<bool use = true> static std::string tenacitas::calendar::now< use >::iso8601_secs () inline static
'now' as a string in the format 'YYYY-MM-DD HH::MM::SS'
Definition at line 118 of file calendar.h.
{
         using namespace std;
         using namespace chrono;
         const time_t _time_t = secs<time_t>();
         stringstream _stream;
         _stream << put_time(std::localtime(&_time_t), "%Y-%m-%d %H:%M:%S");
         return _stream.str();
     }
microsecs()
template<bool use = true> template<typename t_int = uint64_t> static t_int tenacitas::calendar::now< use >::microsecs () inline static
'now' in microseconds
Definition at line 43 of file calendar.h.
{
         return static_cast<t_int>(
             std::chrono::duration_cast<std::chrono::microseconds>(
                 std::chrono::system_clock::now().time_since_epoch())
                 .count());
     }
Referenced by tenacitas::calendar::now< use >::iso8601_microsecs().
millisecs()
template<bool use = true> template<typename t_int = uint64_t> static t_int tenacitas::calendar::now< use >::millisecs () inline static
'now' in milliseconds
Definition at line 84 of file calendar.h.
{
         return static_cast<t_int>(
             std::chrono::duration_cast<std::chrono::milliseconds>(
                 std::chrono::system_clock::now().time_since_epoch())
                 .count());
     }
Referenced by tenacitas::calendar::now< use >::iso8601_millisecs().
minutes()
template<bool use = true> template<typename t_int = uint64_t> static t_int tenacitas::calendar::now< use >::minutes () inline static
'now' in minutes
Definition at line 132 of file calendar.h.
{
         return static_cast<t_int>(
             std::chrono::duration_cast<std::chrono::minutes>(
                 std::chrono::system_clock::now().time_since_epoch())
                 .count());
     }
months()
template<bool use = true> template<typename t_int = uint64_t> static t_int tenacitas::calendar::now< use >::months () inline static
'now' in months
Definition at line 163 of file calendar.h.
{
         return static_cast<t_int>(days() / 30);
     }
References tenacitas::calendar::now< use >::days().
Referenced by tenacitas::calendar::now< use >::years().
secs()
template<bool use = true> template<typename t_int = uint64_t> static t_int tenacitas::calendar::now< use >::secs () inline static
'now' in seconds
Definition at line 109 of file calendar.h.
{
         return static_cast<t_int>(
             std::chrono::duration_cast<std::chrono::seconds>(
                 std::chrono::system_clock::now().time_since_epoch())
                 .count());
     }
years()
template<bool use = true> template<typename t_int = uint64_t> static t_int tenacitas::calendar::now< use >::years () inline static
'now' in years
Definition at line 170 of file calendar.h.
{
         return static_cast<t_int>(months() / 12);
     }
References tenacitas::calendar::now< use >::months().
The documentation for this struct was generated from the following file:
tenacitas/src/tenacitas/calendar.h