tenacitas: tenacitas::logger::internal::log Class Reference
tenacitas::logger::internal::log Class Reference
Thread safe writing of log messages A log message has the format: log-level|timestamp|file-name|thread-id|line-number|contents.
#include <logger.h>
Public Types
typedef std::function< void(std::string &&)> writer
Responsible for actually writing the log message.
Public Member Functions
log ()=default
Default contructor not allowed.
log (const log &)=delete
Copy constructor not allowed.
log (log &&)=delete
Move constructor not allowed.
log & operator= (const log &)=delete
Copy assignment not allowed.
log & operator= (log &&)=delete
Move assignment not allowed.
void * operator new (size_t)=delete
New operator not allowed.
void operator delete (void *)=delete
Delete operator not allowed.
void set_writer (writer p_writer)
Defines the function responsible for actually writing the message.
void set_separator (char p_separator)
Defines the separator to be used in the log messages Default is '|'.
char get_separator () const
Retrieves the separator used in the log messages.
template<typename... t_params>
void trace (const char *p_file, uint16_t p_line, const t_params &... p_params)
Logs message with trace severity Each parameter must implement the output operator. The log message will only be printed if the current log level is level::trace.
template<typename... t_params>
void debug (const char *p_file, uint16_t p_line, const t_params &... p_params)
Logs message with debug severity Each parameter must implement the output operator. The log message will only be printed if the current log level is level::debug or level::trace.
template<typename... t_params>
void info (const char *p_file, uint16_t p_line, const t_params &... p_params)
Logs message with info severity Each parameter must implement the output operator. The log message will only be printed if the current log level is level::info, level::debug or level::trace.
template<typename... t_params>
void warn (const char *p_file, uint16_t p_line, const t_params &... p_params)
Logs message with warn severity Each parameter must implement the output operator. The log message will only be printed if the current log level is level::warn, level::info, level::debug or level::trace.
template<typename... t_params>
void error (const char *p_file, uint16_t p_line, const t_params &... p_params)
Logs message with error severity Each parameter must implement the output operator. level::error messages are allways logged.
template<typename... t_params>
void fatal (const char *p_file, uint16_t p_line, const t_params &... p_params)
Logs message with fatal severity Each parameter must implement the output operator. level::fatal messages are allways logged.
Static Public Attributes
static level g_level {level::warn}
Global log level.
Detailed Description
Thread safe writing of log messages A log message has the format: log-level|timestamp|file-name|thread-id|line-number|contents.
log-level is TRA, DEB, INF, WAR, ERR or FAT; timestamp is a EPOCH number in microsecs; file-name is the name of the file where the message is being writen; thread-id is the id of the thread that is logging; line-number is the number of the line that is logging; contents are the log message specific contents
Definition at line 118 of file logger.h.
Member Typedef Documentation
writer
typedef std::function<void(std::string &&)> tenacitas::logger::internal::log::writer
Responsible for actually writing the log message.
Definition at line 121 of file logger.h.
Constructor & Destructor Documentation
log() [1/3]
tenacitas::logger::internal::log::log () default
Default contructor not allowed.
log() [2/3]
tenacitas::logger::internal::log::log (const log &) delete
Copy constructor not allowed.
log() [3/3]
tenacitas::logger::internal::log::log (log &&) delete
Move constructor not allowed.
Member Function Documentation
debug()
template<typename... t_params> void tenacitas::logger::internal::log::debug (const char * p_file, uint16_t p_line, const t_params &... p_params) inline
Logs message with debug severity Each parameter must implement the output operator. The log message will only be printed if the current log level is level::debug or level::trace.
Template Parameters
t_params are the types of the values to be logged.
Parameters
p_file is the name of the file that is logging
p_line is the line where the logging is done
p_params are the contens of the log message
Definition at line 194 of file logger.h.
{
         write(level::debug, p_file, p_line, p_params...);
     }
References tenacitas::logger::internal::debug.
error()
template<typename... t_params> void tenacitas::logger::internal::log::error (const char * p_file, uint16_t p_line, const t_params &... p_params) inline
Logs message with error severity Each parameter must implement the output operator. level::error messages are allways logged.
Template Parameters
t_params are the types of the values to be logged.
Parameters
p_file is the name of the file that is logging
p_line is the line where the logging is done
p_params are the contens of the log message
Definition at line 247 of file logger.h.
{
         write(level::error, p_file, p_line, p_params...);
     }
References tenacitas::logger::internal::error.
fatal()
template<typename... t_params> void tenacitas::logger::internal::log::fatal (const char * p_file, uint16_t p_line, const t_params &... p_params) inline
Logs message with fatal severity Each parameter must implement the output operator. level::fatal messages are allways logged.
Template Parameters
t_params are the types of the values to be logged.
Parameters
p_file is the name of the file that is logging
p_line is the line where the logging is done
p_params are the contens of the log message
Definition at line 264 of file logger.h.
{
         write(level::fatal, p_file, p_line, p_params...);
     }
References tenacitas::logger::internal::fatal.
get_separator()
char tenacitas::logger::internal::log::get_separator () const inline
Retrieves the separator used in the log messages.
Returns
the value of the separator
Definition at line 160 of file logger.h.
 { return m_separator; }
info()
template<typename... t_params> void tenacitas::logger::internal::log::info (const char * p_file, uint16_t p_line, const t_params &... p_params) inline
Logs message with info severity Each parameter must implement the output operator. The log message will only be printed if the current log level is level::info, level::debug or level::trace.
Template Parameters
t_params are the types of the values to be logged.
Parameters
p_file is the name of the file that is logging
p_line is the line where the logging is done
p_params are the contens of the log message
Definition at line 212 of file logger.h.
{
         write(level::info, p_file, p_line, p_params...);
     }
References tenacitas::logger::internal::info.
operator delete()
void tenacitas::logger::internal::log::operator delete (void *) delete
Delete operator not allowed.
operator new()
void* tenacitas::logger::internal::log::operator new (size_t) delete
New operator not allowed.
operator=() [1/2]
log& tenacitas::logger::internal::log::operator= (const log &) delete
Copy assignment not allowed.
operator=() [2/2]
log& tenacitas::logger::internal::log::operator= (log &&) delete
Move assignment not allowed.
set_separator()
void tenacitas::logger::internal::log::set_separator (char p_separator) inline
Defines the separator to be used in the log messages Default is '|'.
Parameters
p_separator the value of the separator
Definition at line 155 of file logger.h.
 { m_separator = p_separator; }
set_writer()
void tenacitas::logger::internal::log::set_writer (writer p_writer) inline
Defines the function responsible for actually writing the message.
Template Parameters
p_writer the function responsible for actually writing the message
Definition at line 149 of file logger.h.
 { m_writer = p_writer; }
Referenced by tenacitas::logger::set_writer(), tenacitas::logger::set_writer_cerr(), tenacitas::logger::set_writer_clog(), and tenacitas::logger::set_writer_cout().
trace()
template<typename... t_params> void tenacitas::logger::internal::log::trace (const char * p_file, uint16_t p_line, const t_params &... p_params) inline
Logs message with trace severity Each parameter must implement the output operator. The log message will only be printed if the current log level is level::trace.
Template Parameters
t_params are the types of the values to be logged.
Parameters
p_file is the name of the file that is logging
p_line is the line where the logging is done
p_params are the contens of the log message
Definition at line 176 of file logger.h.
{
         write(level::trace, p_file, p_line, p_params...);
     }
References tenacitas::logger::internal::trace.
warn()
template<typename... t_params> void tenacitas::logger::internal::log::warn (const char * p_file, uint16_t p_line, const t_params &... p_params) inline
Logs message with warn severity Each parameter must implement the output operator. The log message will only be printed if the current log level is level::warn, level::info, level::debug or level::trace.
Template Parameters
t_params are the types of the values to be logged.
Parameters
p_file is the name of the file that is logging
p_line is the line where the logging is done
p_params are the contens of the log message
Definition at line 230 of file logger.h.
{
         write(level::warn, p_file, p_line, p_params...);
     }
References tenacitas::logger::internal::warn.
Field Documentation
g_level
level tenacitas::logger::internal::log::g_level {level::warn} static
Global log level.
Definition of the global level.
Definition at line 384 of file logger.h.
Referenced by tenacitas::logger::set_debug_level(), tenacitas::logger::set_info_level(), tenacitas::logger::set_trace_level(), and tenacitas::logger::set_warn_level().
The documentation for this class was generated from the following file:
logger.h