tenacitas: tenacitas::concurrent::business::dispatcher< t_msg > Class Template Reference
tenacitas::concurrent::business::dispatcher< t_msg > Class Template Reference
dispatcher implements a publisher/subscriber pattern
#include <dispatcher.h>
Public Types
typedef std::function< bool(t_msg &&)> work_t
work_t is the type of work function, i.e., the function that will be called in a loop in order to execute some work
Public Member Functions
dispatcher ()=delete
dispatcher default constructor not allowed
dispatcher (const dispatcher &)=delete
dispatcher copy constructor not allowed
dispatcher (dispatcher &&) noexcept=delete
dispatcher move constructor not allowed
dispatcher & operator= (const dispatcher &)=delete
dispatcher copy assigment not allowed
dispatcher & operator= (dispatcher &&) noexcept=delete
dispatcher move assigment not allowed
~dispatcher ()
dispatcher destructor
Static Public Member Functions
static void subscribe (std::function< work_t()> p_work_factory, uint16_t p_num_handlers, std::chrono::milliseconds p_work_timeout)
adds a group of work_t objects to subscribe to handle t_msg objects
static void subscribe (work_t &&p_work, std::chrono::milliseconds p_work_timeout)
subscribe adds a single work_t function to handle t_msg objects
static void publish (const t_msg &p_msg)
handle sends a message to the work_t objects to be handled
Detailed Description
template<typename t_msg>
class tenacitas::concurrent::business::dispatcher< t_msg >
dispatcher implements a publisher/subscriber pattern
Parameters
t_data is the type of the data to be handled. If it is not void, it must be:
default constructible
move constructible
Examples:
/home/rodrigo/tenacitas/code/concurrent/test/correction/dispatcher_000/main.cpp.
Definition at line 37 of file dispatcher.h.
Member Typedef Documentation
work_t
template<typename t_msg> typedef std::function<bool(t_msg&&)> tenacitas::concurrent::business::dispatcher< t_msg >::work_t
work_t is the type of work function, i.e., the function that will be called in a loop in order to execute some work
Definition at line 44 of file dispatcher.h.
Constructor & Destructor Documentation
dispatcher() [1/3]
template<typename t_msg> tenacitas::concurrent::business::dispatcher< t_msg >::dispatcher () delete
dispatcher default constructor not allowed
dispatcher() [2/3]
template<typename t_msg> tenacitas::concurrent::business::dispatcher< t_msg >::dispatcher (const dispatcher< t_msg > &) delete
dispatcher copy constructor not allowed
dispatcher() [3/3]
template<typename t_msg> tenacitas::concurrent::business::dispatcher< t_msg >::dispatcher (dispatcher< t_msg > &&) delete noexcept
dispatcher move constructor not allowed
~dispatcher()
template<typename t_msg> tenacitas::concurrent::business::dispatcher< t_msg >::~dispatcher () inline
dispatcher destructor
Stops all the thread_pool
Definition at line 64 of file dispatcher.h.
References cerr_debug.
     {
         cerr_debug("leaving");
         for (thread_pool_t& _pool : m_thread_pool_list) {
             _pool.stop();
         }
     }
Member Function Documentation
operator=() [1/2]
template<typename t_msg> dispatcher& tenacitas::concurrent::business::dispatcher< t_msg >::operator= (const dispatcher< t_msg > &) delete
dispatcher copy assigment not allowed
operator=() [2/2]
template<typename t_msg> dispatcher& tenacitas::concurrent::business::dispatcher< t_msg >::operator= (dispatcher< t_msg > &&) delete noexcept
dispatcher move assigment not allowed
publish()
template<typename t_msg> static void tenacitas::concurrent::business::dispatcher< t_msg >::publish (const t_msg & p_msg) inline static
handle sends a message to the work_t objects to be handled
Parameters
p_msg an instance of t_msg
Examples:
/home/rodrigo/tenacitas/code/concurrent/test/correction/dispatcher_000/main.cpp.
Definition at line 130 of file dispatcher.h.
References cerr_warn.
Referenced by publisher_1::operator()(), publisher_2::operator()(), and publisher_3::operator()().
     {
         if (m_thread_pool_list.empty()) {
             cerr_warn("there are no subscribers for ", p_msg);
         }
         for (thread_pool_t& _pool : m_thread_pool_list) {
             _pool.handle(p_msg);
         }
     }
subscribe() [1/2]
template<typename t_msg> static void tenacitas::concurrent::business::dispatcher< t_msg >::subscribe (std::function< work_t()> p_work_factory, uint16_t p_num_handlers, std::chrono::milliseconds p_work_timeout) inline static
adds a group of work_t objects to subscribe to handle t_msg objects
Parameters
p_work_factory is a function that creates work_t objects
p_num_handlers is the number of work_t objects that we want to "fight" among each other to handle a t_msg object
p_work_timeout is the maximum amount of time for a work_t function can take to handle a t_msg instance
Definition at line 80 of file dispatcher.h.
References tenacitas::concurrent::business::thread_pool< t_data >::add_work(), tenacitas::logger::business::configure_cerr_log(), and tenacitas::concurrent::business::thread_pool< t_data >::run().
     {
         // initiating the cerr_log
         tenacitas::logger::business::configure_cerr_log();
         // creating a \p thread_pool
         thread_pool_t _thread_pool;
         // adding the \p work_t functions
         _thread_pool.add_work(p_num_handlers, p_work_factory, p_work_timeout);
         // running the \p thread_pool
         _thread_pool.run();
         // adding the \p thread_pool to the list
         m_thread_pool_list.push_back(std::move(_thread_pool));
     }
subscribe() [2/2]
template<typename t_msg> static void tenacitas::concurrent::business::dispatcher< t_msg >::subscribe (work_t && p_work, std::chrono::milliseconds p_work_timeout) inline static
subscribe adds a single work_t function to handle t_msg objects
Parameters
p_work the work_t function that will handle a t_msg object
p_work_timeout is the maximum amount of time for a work_t function can take to handle a t_msg instance
Definition at line 107 of file dispatcher.h.
References tenacitas::concurrent::business::thread_pool< t_data >::add_work(), tenacitas::logger::business::configure_cerr_log(), and tenacitas::concurrent::business::thread_pool< t_data >::run().
     {
         // initiating the cerr_log
         tenacitas::logger::business::configure_cerr_log();
         // creating a \p thread_pool
         thread_pool_t _thread_pool;
         // adding the \p work_t functions
         _thread_pool.add_work(std::move(p_work), p_work_timeout);
         // running the \p thread_pool
         _thread_pool.run();
         // adding the \p thread_pool to the list
         m_thread_pool_list.push_back(std::move(_thread_pool));
     }
The documentation for this class was generated from the following file:
/home/rodrigo/tenacitas/code/concurrent/business/dispatcher.h