tenacitas: tenacitas::calendar::business Namespace Reference
tenacitas::calendar::business Namespace Reference
Classes
struct epoch
Functions
int64_t sec2mil (int64_t p_secs)
int64_t min2sec (int64_t p_min)
int64_t min2mil (int64_t p_min)
int64_t hr2min (int64_t p_hr)
int64_t hr2sec (int64_t p_hr)
int64_t hr2mil (int64_t p_hr)
int64_t day2hr (int64_t p_day)
int64_t day2min (int64_t p_day)
int64_t day2sec (int64_t p_day)
int64_t day2mil (int64_t p_day)
Function Documentation
day2hr()
int64_t tenacitas::calendar::business::day2hr (int64_t p_day) inline
Definition at line 47 of file conversions.h.
Referenced by day2mil(), day2min(), and day2sec().
 {
     return p_day * 24;
 }
day2mil()
int64_t tenacitas::calendar::business::day2mil (int64_t p_day) inline
Definition at line 65 of file conversions.h.
References day2hr(), hr2min(), min2sec(), and sec2mil().
 {
     return sec2mil(min2sec(hr2min(day2hr(p_day))));
 }
day2min()
int64_t tenacitas::calendar::business::day2min (int64_t p_day) inline
Definition at line 53 of file conversions.h.
References day2hr(), and hr2min().
 {
     return hr2min(day2hr(p_day));
 }
day2sec()
int64_t tenacitas::calendar::business::day2sec (int64_t p_day) inline
Definition at line 59 of file conversions.h.
References day2hr(), hr2min(), and min2sec().
 {
     return min2sec(hr2min(day2hr(p_day)));
 }
hr2mil()
int64_t tenacitas::calendar::business::hr2mil (int64_t p_hr) inline
Definition at line 41 of file conversions.h.
References hr2min(), min2sec(), and sec2mil().
 {
     return sec2mil(min2sec(hr2min(p_hr)));
 }
hr2min()
int64_t tenacitas::calendar::business::hr2min (int64_t p_hr) inline
Definition at line 29 of file conversions.h.
Referenced by day2mil(), day2min(), day2sec(), hr2mil(), and hr2sec().
 {
     return p_hr * 60;
 }
hr2sec()
int64_t tenacitas::calendar::business::hr2sec (int64_t p_hr) inline
Definition at line 35 of file conversions.h.
References hr2min(), and min2sec().
 {
     return min2sec(hr2min(p_hr));
 }
min2mil()
int64_t tenacitas::calendar::business::min2mil (int64_t p_min) inline
Definition at line 23 of file conversions.h.
References min2sec(), and sec2mil().
 {
     return sec2mil(min2sec(p_min));
 }
min2sec()
int64_t tenacitas::calendar::business::min2sec (int64_t p_min) inline
Definition at line 17 of file conversions.h.
Referenced by day2mil(), day2sec(), hr2mil(), hr2sec(), and min2mil().
 {
     return p_min * 60;
 }
sec2mil()
int64_t tenacitas::calendar::business::sec2mil (int64_t p_secs) inline
Definition at line 11 of file conversions.h.
Referenced by day2mil(), hr2mil(), and min2mil().
 {
     return p_secs * 1000;
 }