tenacitas: tenacitas::concurrent::business::sleeping_loop< t_data > Struct Template Reference
tenacitas::concurrent::business::sleeping_loop< t_data > Struct Template Reference
sleeping_loop allows a function (object) to be called in a loop that is executed asyncronously at a user defined period of time.
#include <sleeping_loop.h>
Public Types
typedef loop_traits< t_data >::work_t work_t
work_t is the type of work function, i.e., the function that will be called in a loop in order to execute some work
typedef loop_traits< t_data >::provide_t provide_t
provide_t is the type of function that provides data to the work function during the loop execution, if t_data is not void
Public Member Functions
sleeping_loop (std::chrono::milliseconds p_interval, work_t &&p_work, std::chrono::milliseconds p_timeout, provide_t &&p_provide)
sleeping_loop creates a sleeping_loop object, when bt_data != void, and a provider is necessary
sleeping_loop (std::chrono::milliseconds p_interval, work_t &&p_work, std::chrono::milliseconds p_timeout)
sleeping_loop creates a sleeping_loop object, when bt_data == void, and a provider is not necessary
sleeping_loop ()=delete
default constructor not allowed
sleeping_loop (const sleeping_loop &)=delete
copy constructor not allowed
sleeping_loop (sleeping_loop &&p_sleep) noexcept
move constructor
~sleeping_loop ()
destructor interrupts the loop
sleeping_loop & operator= (const sleeping_loop &)=delete
copy assignment not allowed
sleeping_loop & operator= (sleeping_loop &&p_sleep) noexcept
move assignment
bool is_stopped () const
is_stopped
work_t get_work () const
get_work
provide_t get_provide () const
get_provide
std::chrono::milliseconds get_timeout () const
get_timeout
std::chrono::milliseconds get_interval () const
get_interval
void run ()
run starts the loop
void stop ()
stop stops the loop
Detailed Description
template<typename t_data>
struct tenacitas::concurrent::business::sleeping_loop< t_data >
sleeping_loop allows a function (object) to be called in a loop that is executed asyncronously at a user defined period of time.
Parameters
t_data is the type of the data to be handled. If it is not void, it must be:
default constructible
move constructible
Examples:
/home/rodrigo/tenacitas/code/concurrent/test/correction/dispatcher_000/main.cpp, /home/rodrigo/tenacitas/code/concurrent/test/correction/sleeping_loop_002/main.cpp, /home/rodrigo/tenacitas/code/concurrent/test/correction/thread_pool_097/main.cpp, /home/rodrigo/tenacitas/code/logger/test/correction/cerr_log_single/main.cpp, /home/rodrigo/tenacitas/code/logger/test/correction/cout_log_multi/main.cpp, and /home/rodrigo/tenacitas/code/logger/test/correction/file_log_single/main.cpp.
Definition at line 36 of file sleeping_loop.h.
Member Typedef Documentation
provide_t
template<typename t_data > typedef loop_traits<t_data>::provide_t tenacitas::concurrent::business::sleeping_loop< t_data >::provide_t
provide_t is the type of function that provides data to the work function during the loop execution, if t_data is not void
Definition at line 48 of file sleeping_loop.h.
work_t
template<typename t_data > typedef loop_traits<t_data>::work_t tenacitas::concurrent::business::sleeping_loop< t_data >::work_t
work_t is the type of work function, i.e., the function that will be called in a loop in order to execute some work
Definition at line 42 of file sleeping_loop.h.
Constructor & Destructor Documentation
sleeping_loop() [1/5]
template<typename t_data > tenacitas::concurrent::business::sleeping_loop< t_data >::sleeping_loop (std::chrono::milliseconds p_interval, work_t && p_work, std::chrono::milliseconds p_timeout, provide_t && p_provide) inline
sleeping_loop creates a sleeping_loop object, when bt_data != void, and a provider is necessary
Parameters
p_interval the amount of time that the loop will sleep between executions
p_work function that will be executed each time the loop wakes up
p_timeout amount of time that the loop will wait for p_work to execute
p_provide function that will provide data to the work function, each time the loop wakes up
Definition at line 62 of file sleeping_loop.h.
       : m_async(std::move(p_work),
                 std::move(p_timeout),
                 [this]() -> bool { return this->break_loop(); },
                 std::move(p_provide))
       , m_interval(p_interval)
     {}
sleeping_loop() [2/5]
template<typename t_data > tenacitas::concurrent::business::sleeping_loop< t_data >::sleeping_loop (std::chrono::milliseconds p_interval, work_t && p_work, std::chrono::milliseconds p_timeout) inline
sleeping_loop creates a sleeping_loop object, when bt_data == void, and a provider is not necessary
Parameters
p_interval the amount of time that the loop will sleep between executions
p_work function that will be executed each time the loop wakes up
p_timeout amount of time that the loop will wait for p_work to execute
Definition at line 83 of file sleeping_loop.h.
References tenacitas::concurrent::business::sleeping_loop< t_data >::sleeping_loop().
       : m_async(std::move(p_work),
                 std::move(p_timeout),
                 [this]() -> bool { return this->break_loop(); },
                 []() -> void {})
       , m_interval(p_interval)
     {}
sleeping_loop() [3/5]
template<typename t_data > tenacitas::concurrent::business::sleeping_loop< t_data >::sleeping_loop () delete
default constructor not allowed
Referenced by tenacitas::concurrent::business::sleeping_loop< t_data >::sleeping_loop().
sleeping_loop() [4/5]
template<typename t_data > tenacitas::concurrent::business::sleeping_loop< t_data >::sleeping_loop (const sleeping_loop< t_data > &) delete
copy constructor not allowed
sleeping_loop() [5/5]
template<typename t_data > tenacitas::concurrent::business::sleeping_loop< t_data >::sleeping_loop (sleeping_loop< t_data > && p_sleep) inline noexcept
move constructor
Definition at line 100 of file sleeping_loop.h.
     {
         move(std::move(p_sleep));
     }
~sleeping_loop()
template<typename t_data > tenacitas::concurrent::business::sleeping_loop< t_data >::~sleeping_loop () inline
destructor interrupts the loop
Definition at line 106 of file sleeping_loop.h.
References cerr_debug, tenacitas::concurrent::business::sleeping_loop< t_data >::operator=(), and tenacitas::concurrent::business::sleeping_loop< t_data >::stop().
     {
         cerr_debug(this, " destructor");
         stop();
     }
Member Function Documentation
get_interval()
template<typename t_data > std::chrono::milliseconds tenacitas::concurrent::business::sleeping_loop< t_data >::get_interval () const inline
get_interval
Returns
the interval of loop execution
Definition at line 158 of file sleeping_loop.h.
 { return m_interval; }
get_provide()
template<typename t_data > provide_t tenacitas::concurrent::business::sleeping_loop< t_data >::get_provide () const inline
get_provide
Returns
a copy of the function that provides an instance of t_data, if available, to the work function
Definition at line 142 of file sleeping_loop.h.
 { return m_async.get_provide(); }
get_timeout()
template<typename t_data > std::chrono::milliseconds tenacitas::concurrent::business::sleeping_loop< t_data >::get_timeout () const inline
get_timeout
Returns
the amount of time that the loop will wait for the work function to finish
Definition at line 149 of file sleeping_loop.h.
     {
         return m_async.get_timeout();
     }
get_work()
template<typename t_data > work_t tenacitas::concurrent::business::sleeping_loop< t_data >::get_work () const inline
get_work
Returns
a copy of the function that executes a defined work in each round of the loop
Definition at line 135 of file sleeping_loop.h.
 { return m_async.get_work(); }
is_stopped()
template<typename t_data > bool tenacitas::concurrent::business::sleeping_loop< t_data >::is_stopped () const inline
is_stopped
Returns
true if the loop is not running; false othewise
Definition at line 128 of file sleeping_loop.h.
 { return m_async.is_stopped(); }
operator=() [1/2]
template<typename t_data > sleeping_loop& tenacitas::concurrent::business::sleeping_loop< t_data >::operator= (const sleeping_loop< t_data > &) delete
copy assignment not allowed
Referenced by tenacitas::concurrent::business::sleeping_loop< t_data >::~sleeping_loop().
operator=() [2/2]
template<typename t_data > sleeping_loop& tenacitas::concurrent::business::sleeping_loop< t_data >::operator= (sleeping_loop< t_data > && p_sleep) inline noexcept
move assignment
Definition at line 116 of file sleeping_loop.h.
     {
         if (this != &p_sleep) {
             move(std::move(p_sleep));
         }
         return *this;
     }
run()
template<typename t_data > void tenacitas::concurrent::business::sleeping_loop< t_data >::run () inline
run starts the loop
Examples:
/home/rodrigo/tenacitas/code/concurrent/test/correction/dispatcher_000/main.cpp, /home/rodrigo/tenacitas/code/concurrent/test/correction/sleeping_loop_002/main.cpp, /home/rodrigo/tenacitas/code/logger/test/correction/cerr_log_single/main.cpp, /home/rodrigo/tenacitas/code/logger/test/correction/cout_log_multi/main.cpp, and /home/rodrigo/tenacitas/code/logger/test/correction/file_log_single/main.cpp.
Definition at line 161 of file sleeping_loop.h.
References cerr_debug.
Referenced by cerr_log_single::operator()(), file_log_single::operator()(), cerr_log_multi::operator()(), sleeping_loop_002::operator()(), dispatcher_000::operator()(), and tenacitas::concurrent::business::sleeping_loop< t_data >::stop().
     {
         if (!m_async.is_stopped()) {
             cerr_debug(this,
                        " not running async loop because it was not stopped");
             return;
         }
         cerr_debug(this, " running async loop");
         m_async.run();
     }
stop()
template<typename t_data > void tenacitas::concurrent::business::sleeping_loop< t_data >::stop () inline
stop stops the loop
Definition at line 173 of file sleeping_loop.h.
References cerr_debug, and tenacitas::concurrent::business::sleeping_loop< t_data >::run().
Referenced by tenacitas::concurrent::business::sleeping_loop< t_data >::~sleeping_loop().
     {
         if (m_async.is_stopped()) {
             cerr_debug(this,
                        " not stopping async loop because it was not running");
             return;
         }
         cerr_debug(this, " stop");
         m_cond_var.notify_all();
         cerr_debug(this, " all notified, and m_async = ", &m_async);
         m_async.stop();
     }
The documentation for this struct was generated from the following file:
/home/rodrigo/tenacitas/code/concurrent/business/sleeping_loop.h