@startuml
title Software Structure - version 1
[machine_human_interface] --> [business_local]
[business_local] --> [business_client]
[business_client] --> [communicator_business]
[communicator_business] --> [business_server]
[business_server] --> [business]
[business] --> [persistence_local]
[persistence_local] --> [persistence_client]
[persistence_client] --> [communicator_persistence]
[communicator_persistence] --> [persistence_server]
[persistence_server] --> [persistence]
[machine_human_interface] -down-> [entities]
[business_local] --> [entities]
[business_client] --> [entities]
[business] --> [entities]
[business_server] -->  [entities]
[persistence_local] --> [entities]
[persistence_client] --> [entities]
[persistence] ---> [entities]
[persistence_server] -->  [entities]
note "communicator_business and communicator_persistence are the same. \nThey are separated to display a better looking diagram" as N1
@enduml
