@startuml

hide empty members
allow_mixing
hide circle

skinparam groupInheritance 3

class site <<directory, namespace>>
class project <<directory, namespace, build_file>>
class product <<directory, build_file>>
class layer <<directory, namespace>>

site *-- "*" project
project *-- "*" layer
layer <|--- bus
layer <|-- ent 
layer <|-- per 
layer <|-- com
layer <|--- uif
layer <|-- ser

project *-- "*" product
product <|- lib
product <|-- pgm
product <|-- header

product *-- "*" layer

class code <<directory>>
class build <<directory>>

project ..> code
project ..> build
code ..> layer
build .right.> product

uif -right-> bus
uif --> ent
bus --> ent
bus -right-> per
bus --> com
per --> ent
com --> ent
per --> com
com -right-> ser
ser --> ent

pgm --> pgm
pgm -> lib
lib --> lib
pgm -> header
lib --> header
@enduml