tenacitas: tenacitas::tester::test< use > Struct Template Reference
tenacitas::tester::test< use > Struct Template Reference
The test struct executes tests implemented in classes.
#include <tester.h>
Public Member Functions
test (int argc, char **argv) noexcept
Constructor If '–desc' is passed, operator() will print a description of the tests. If '–exec' is passed, operator() will execute the tests If '–exec { <test-name-1> <test-name-2> ... }' is passed, operator() will execute the tests between '{' and '}'.
test ()=delete
Default constructor not allowed.
test (const test &)=delete
Copy constructor not allowed.
test (test &&)=delete
Copy constructor not allowed.
test & operator= (const test &)=delete
Copy assignment not allowed.
test & operator= (test &&)=delete
Move assignment not allowed.
template<typename t_test_class >
void run (const std::string &p_test_name) noexcept
Executes the test If the test passes, the message "SUCCESS for <name>" will be printed; if the test does not pass, the message "FAIL for <name>" will be printed; if an error occurr while executing the test , the messae "ERROR for <name> <desc>" will be printed.
Detailed Description
template<bool use = true>
struct tenacitas::tester::test< use >
The test struct executes tests implemented in classes.
Template Parameters
use makes tenacitas::tester::test to be compiled only if actually used
 #include <iostream>
 #include <string>
 #include <tester/test.h>
 using namespace tenacitas;
 struct test_ok {
   bool operator()() { return true; }
   static std::string desc() { return "an ok test"; }
 };
 struct test_fail {
   bool operator()() { return true; }
   static std::string desc() { return "a fail test"; }
 };
 struct test_error {
  bool operator()() {
    try {
      throw std::runtime_error("test function raised an exception");
      return false;
    } catch (const std::exception &_ex) {
      std::cerr << "'test_error' raised '" << _ex.what() << "'" << std::endl;
      return true;
    }
  }
  static std::string desc() { return "an eror test"; }
};
  int main(int argc, char **argv) {
  try {
    tester::test _tester(argc, argv);
    run_test(_tester, test_ok);
    run_test(_tester, test_fail);
    run_test(_tester, test_error);
  } catch (std::exception &_ex) {
    std::cout << "EXCEPTION: '" << _ex.what() << "'" << std::endl;
  }
}
Definition at line 85 of file tester.h.
Constructor & Destructor Documentation
test()
template<bool use = true> tenacitas::tester::test< use >::test (int argc, char ** argv) inline noexcept
Constructor If '–desc' is passed, operator() will print a description of the tests. If '–exec' is passed, operator() will execute the tests If '–exec { <test-name-1> <test-name-2> ... }' is passed, operator() will execute the tests between '{' and '}'.
Parameters
argc number of strings in argv
argv parameters passed to the program
Definition at line 97 of file tester.h.
         : m_argc(argc)
         , m_argv(argv) {
         m_pgm_name = m_argv[0];
         try {
             program::options_t _options;
             _options.parse(m_argc, m_argv);
             if (_options.get_bool_param("exec")) {
                 m_execute_tests = true;
             } else if (_options.get_bool_param("desc")) {
                 m_print_desc = true;
             } else {
                 std::optional<std::list<program::options_t<>::value>> _maybe =
                     _options.get_set_param("exec");
                 if (_maybe) {
                     m_execute_tests = true;
                     std::list<program::options_t<>::value> _tests_to_exec =
                         std::move(*_maybe);
                     m_tests_to_exec.insert(_tests_to_exec.begin(),
                                            _tests_to_exec.end());
                 }
             }
             if ((!m_execute_tests) && (!m_print_desc)) {
                 print_mini_howto();
             }
         } catch (std::exception &_ex) {
             std::cout << "EXCEPTION '" << _ex.what() << "'" << std::endl;
             return;
         }
     }
References tenacitas::program::options_t< use >::get_bool_param(), tenacitas::program::options_t< use >::get_set_param(), and tenacitas::program::options_t< use >::parse().
Member Function Documentation
run()
template<bool use = true> template<typename t_test_class > void tenacitas::tester::test< use >::run (const std::string & p_test_name) inline noexcept
Executes the test If the test passes, the message "SUCCESS for <name>" will be printed; if the test does not pass, the message "FAIL for <name>" will be printed; if an error occurr while executing the test , the messae "ERROR for <name> <desc>" will be printed.
Template Parameters
t_test_class must implement:
bool operator()()
static std::string desc()
You can use the macro 'run_test' defined above, instead of calling this method
Definition at line 164 of file tester.h.
{
         using namespace std;
         try {
             if (m_print_desc) {
                 cout << string(p_test_name.size(), '-') << '\n';
                 cout << p_test_name << ": " << t_test_class::desc() << "\n"
                      << endl;
                 return;
             }
             if (m_execute_tests) {
                 if (!m_tests_to_exec.empty()) {
                     if ((std::find(m_tests_to_exec.begin(),
                                    m_tests_to_exec.end(), p_test_name)) !=
                         m_tests_to_exec.end()) {
                         exec<t_test_class>(p_test_name);
                     }
                 } else {
                     exec<t_test_class>(p_test_name);
                 }
             }
         } catch (std::exception &_ex) {
             std::cout << "EXCEPTION '" << _ex.what() << "'" << std::endl;
             return;
         }
     }
The documentation for this struct was generated from the following file:
tester.h