tenacitas.lib: tenacitas::async Namespace Reference
tenacitas::async Namespace Reference
support for async (asynchronous) programming
Namespaces
internal
Data Structures
struct reader_t
Asynchronous reader.
struct result_traits
struct result_traits< void >
struct sleeping_loop_t
Periodically executes a function.
Typedefs
typedef uint8_t priority
Defines the priority of a handling for an event among other handlings of that event.
typedef number::id handling_id
Identifier of a handling It is simply a, hopefully, unique number.
template<typename t_event >
using handler_t = std::function< void(ptr< bool > p_bool, t_event &&p_event)>
Type of function that handles an event.
Functions
template<typename t_time , typename t_function , typename... t_params>
result_traits< std::invoke_result_t< t_function, type::ptr< bool >, t_params... > >::result execute (t_time p_timeout, t_function &p_function, t_params &&... p_params)
Synchronous function with collaborative timeout control.
template<typename t_event , typename t_time >
static handling_id add_handling (t_time p_timeout=5s, priority p_priority=125)
Adds a handling to receive events to be handled.
template<typename t_event , typename t_time >
static handling_id add_handling (handler_t< t_event > &&p_handler, t_time p_timeout=5s, priority p_priority=125)
Adds a handling to receive events to be handled, and adds a handler.
template<typename t_event >
static void set_priority (const handling_id &p_handling, priority p_priority)
Defines the priority of a handling.
template<typename t_event >
static std::optional< priority > get_priority (const handling_id &p_handling)
Retrieves the priority of a handling The priority of the handling defines the order in which a event will be added.
template<typename t_event >
static void dispatch (const t_event &p_event)
Dispatches an event to all handlings associated to the event.
template<typename t_event >
static void dispatch (t_event &&p_event)
Dispatches an event to all handlings associated to the event.
template<typename t_event >
static void add_handler (const handling_id &p_handling, handler_t< t_event > &&p_handler)
Adds a handler to a handling.
template<typename t_event >
static void add_handler (const handling_id &p_handling, uint16_t p_num_workers, std::function< handler_t< t_event >()> p_factory)
Adds a bunch of handlers to a handling.
template<typename t_event , typename t_time >
static handling_id add_handler (handler_t< t_event > &&p_handler, t_time p_timeout, priority p_priority=125)
Adds a handling to receive events to be handled, and adds a handler to it.
Detailed Description
support for async (asynchronous) programming
The UML below shows the basic structure of the async namespace
The central concept is an t_event. A t_event is a struct that contains data about an interesting event in the application. It can be, for example, a incoming message from a network connection, or a user menu choice.
A handler_t is a function class that will handle a t_event. We can see in the tenacitas::async::handler_t signature that it also receives a std::share_ptr<bool> object. Through this pointer a handler_t function may be informed that its execution took more time than specified, so that it can make the decision to stop running.
A handling_t defines a type of handling for a t_event, and can group as many handler_t objects as necessary. For example, a user menu choice can generate a log message, a message sent to a remote program, and to change the color of widget in the user interface. Each one of this actions is a handling_t. Besides, it is possible to define one handler for the logging handling, five handlers to the network message handling, and two for the widget color changing. When the user makes its menu choice, the five handler_t objects in the message network handling_t will "fight each other" to get the t_event to handle.
Each handling_t defines a timeout applies to all its handler_t objects, and it is possible to define a tenacitas::async::priority for a handling_t, so that the higher priority will receive a t_event before the others handling_t.
The dispatcher_t class is responsible for managing the creation of handling_t objects, adding handler_t objects to a handling_t, and dispatching t_event objects to the handing_t.
In order to make it easier to deal with these classes, the async namespace implements a set of functions: tenacitas::async::add_handling, tenacitas::async::add_handler, tenacitas::async::set_priority and tenacitas::async::dispatch, with some variations.
The sleeping_loop_t allows a function to be executed in a defined interval. It is usefull, among others, to dispatch t_event, in order to simulate an actual event generation and handling.
Please, look at the Examples section for examples on how to use these functions and classes.
Typedef Documentation
handler_t
template<typename t_event > using tenacitas::async::handler_t = typedef std::function<void(ptr<bool> p_bool, t_event &&p_event)>
Type of function that handles an event.
Template Parameters
t_event is the type of event that will be handled It must be default constructible, copy constructible, copy assignable, move constructible, move assignable and must have the output operator (<<) defined
Parameters
p_bool is a means for the object that will call the handler function to inform that the handler may stop working, as the timeout defined for it to finish its work has expired. So, the handler function should check, between its instructions, for the value o p_bool, in order to continue to the following instruction, or to interrupt its execution
p_event is the event to be handled
Definition at line 135 of file async.h.
handling_id
typedef number::id tenacitas::async::handling_id
Identifier of a handling It is simply a, hopefully, unique number.
Definition at line 118 of file async.h.
priority
typedef uint8_t tenacitas::async::priority
Defines the priority of a handling for an event among other handlings of that event.
Definition at line 114 of file async.h.
Function Documentation
add_handler() [1/3]
template<typename t_event > static void tenacitas::async::add_handler (const handling_id & p_handling, handler_t< t_event > && p_handler) inline static
Adds a handler to a handling.
It is possible to add many handlers to the same handling. Those handlers will compete with each other to handle a added event.
Template Parameters
t_event is the type of event to be added to the queue
Parameters
p_handling is the identifier of the handling to which this handler will be added to
p_handler is the function that will handle an event added to the handling
Definition at line 1423 of file async.h.
{
     internal::get_dispatcher<t_event>().add_handler(p_handling,
                                                     std::move(p_handler));
 }
add_handler() [2/3]
template<typename t_event > static void tenacitas::async::add_handler (const handling_id & p_handling, uint16_t p_num_workers, std::function< handler_t< t_event >()> p_factory) inline static
Adds a bunch of handlers to a handling.
It is possible to add many handlers to the same handling. Those handlers will compete with each other to handle a added event.
Template Parameters
t_event is the type of event to be added to the queue
Parameters
p_handling_id is the identifier of the handling to which this handler will be added to
p_num_workers defines the number of handler functions to be added
p_factory is a function that creates handler function
Definition at line 1444 of file async.h.
{
     internal::get_dispatcher<t_event>().add_handler(p_handling, p_num_workers,
                                                     p_factory);
 }
add_handler() [3/3]
template<typename t_event , typename t_time > static handling_id tenacitas::async::add_handler (handler_t< t_event > && p_handler, t_time p_timeout, priority p_priority = 125) inline static
Adds a handling to receive events to be handled, and adds a handler to it.
It is possible to add many handlers to the same handling. Those handlers will compete with each other to handle a added event.
Template Parameters
t_event is the type of event to be added to the queue
t_time is the type of time used to define the timeout
Parameters
p_handling_id is the identifier of the handling to which this handler will be added to
p_handler is the function that will handle an event added to the handling
p_timeout is the maximum amount of time that the handler function will have to complete its work.
p_priority is the priority of the queue. This defines the order that the event will be placed in the queue.
Returns
the handling id of the handling added
Definition at line 1475 of file async.h.
{
     number::id _id = add_handling<t_event>(p_timeout, p_priority);
     internal::get_dispatcher<t_event>().add_handler(_id, std::move(p_handler));
     return _id;
 }
Referenced by tenacitas::async::internal::handling_t< t_event >::add_handler(), and tenacitas::async::internal::dispatcher_t< t_event >::add_handling().
add_handling() [1/2]
template<typename t_event , typename t_time > static handling_id tenacitas::async::add_handling (handler_t< t_event > && p_handler, t_time p_timeout = 5s, priority p_priority = 125) inline static
Adds a handling to receive events to be handled, and adds a handler.
Template Parameters
t_event is the type of event to be added to the queue
t_time is the type of time used to define the timeout
Parameters
p_handler is the handler function to be added
p_timeout is the maximum amount of time that the handler function will have to complete its work.
p_priority is the priority of the queue. This defines the order that the event will be placed in the queue.
Returns
the handling id of the handling added
Definition at line 1350 of file async.h.
{
     return internal::get_dispatcher<t_event>().add_handling(
         std::move(p_handler), p_timeout, p_priority);
 }
Referenced by tenacitas::async::internal::dispatcher_t< t_event >::add_handling().
add_handling() [2/2]
template<typename t_event , typename t_time > static handling_id tenacitas::async::add_handling (t_time p_timeout = 5s, priority p_priority = 125) inline static
Adds a handling to receive events to be handled.
Template Parameters
t_event is the type of event to be added to the handling
t_time is the type of time used to define the timeout
Parameters
p_timeout is the maximum amount of time that the handler function will have to complete its work.
p_priority is the priority of the queue. This defines the order that the event will be placed in the queue.
Returns
the handling id of the handling added
Definition at line 1328 of file async.h.
{
     return internal::get_dispatcher<t_event>().add_handling(p_timeout,
                                                             p_priority);
 }
dispatch() [1/2]
template<typename t_event > static void tenacitas::async::dispatch (const t_event & p_event) inline static
Dispatches an event to all handlings associated to the event.
Template Parameters
t_event is the type of event to be added to the handling
Parameters
p_event is the event to be copied to all handlings
Examples
application_000/main.cpp, dispatcher_000/main.cpp, dispatcher_001/main.cpp, dispatcher_002/main.cpp, and reader_000/main.cpp.
Definition at line 1396 of file async.h.
{
     internal::get_dispatcher<t_event>().send(p_event);
 }
dispatch() [2/2]
template<typename t_event > static void tenacitas::async::dispatch (t_event && p_event) inline static
Dispatches an event to all handlings associated to the event.
Template Parameters
t_event is the type of event to be added to the handling
Parameters
p_event is the event to be copied to all handlings
Definition at line 1406 of file async.h.
{
     internal::get_dispatcher<t_event>().send(p_event);
 }
Referenced by tenacitas::async::reader_t< t_data >::start().
execute()
template<typename t_time , typename t_function , typename... t_params> result_traits< std::invoke_result_t<t_function, type::ptr<bool>, t_params...> >::result tenacitas::async::execute (t_time p_timeout, t_function & p_function, t_params &&... p_params)
Synchronous function with collaborative timeout control.
Template Parameters
t_time type of time used to define timeout. It must be one of the defined in std::chrono, such as std::chrono::seconds
t_function is the type of function that will be executed synchronously. It must have this signature:
return-type operator()(std::shared_ptr<bool>, params-type...)
Where return-type is the type returned by the function. It can void, or any other type or class.
Where std::shared_ptr<bool> is a pointer to bool that will become true if the function being executed exceeds the time limit to execute. It is how the execute function tells the function being executed that a timeout occurred. So, the function being executed should, as much as possible, during its execution, to check for the value of this pointer. If it becomes true, the function must return, as its execution is no longer necessary, neither its return, if any, is expected.
Where params-type is a variadic number of parameters, if any, as the function being executed needs.
Parameters
p_timeout is the amount of time the function being executed has to finish its execution
p_function is the function being executed, with the signature described above
p_params are the parameters expected by p_function, if any
Returns
If p_function returns, say a int16_t, execute returns std::optional<int16_t>, which will contain a int16_t if p_function executes in less than p_timeout time, i.e., no timeout occurrs; otherwise no value is returned in the std::optional.
However, if p_function's return is void, then execute returns a bool, which is true if no timeout occurrs; or false otherwise.
Examples
executer_000/main.cpp.
Definition at line 317 of file async.h.
{
     typedef internal::executer_t<
         std::invoke_result_t<t_function, type::ptr<bool>, t_params...>>
         executer;
     executer _executer;
     return _executer(p_timeout, p_function,
                      std::forward<t_params>(p_params)...);
 }
Referenced by tenacitas::async::reader_t< t_data >::stop().
get_priority()
template<typename t_event > static std::optional<priority> tenacitas::async::get_priority (const handling_id & p_handling) inline static
Retrieves the priority of a handling The priority of the handling defines the order in which a event will be added.
Template Parameters
t_event is the type of event to be added to the queue
Parameters
p_handling is the identifier of the queue
Returns
The priority of the queue, if a handling with handling_id was found
Definition at line 1386 of file async.h.
{
     return internal::get_dispatcher<t_event>().get_priority(p_handling);
 }
set_priority()
template<typename t_event > static void tenacitas::async::set_priority (const handling_id & p_handling, priority p_priority) inline static
Defines the priority of a handling.
The priority of the handling defines the order in which an event will be handled
Template Parameters
t_event is the type of event to be added to the queue
Parameters
p_handling is the identifier of the handling
p_priority is the priority of the handling. This defines the order that the event will be placed in the handling.
Definition at line 1369 of file async.h.
{
     internal::get_dispatcher<t_event>().set_priority(p_handling, p_priority);
 }