tenacitas: tenacitas::concurrent::business::thread Class Reference
tenacitas::concurrent::business::thread Class Reference
The thread class is a wrapper for the std::thread, which joins in destructor and move assignment.
#include <thread.h>
Public Member Functions
thread (std::function< void()> &&p_func)
thread constructor
thread ()=default
thread (const thread &)=delete
thread (thread &&) noexcept=default
thread & operator= (const thread &)=delete
thread & operator= (thread &&p_th) noexcept
operator = move joins the 'this' thread, if the thread is still running
void join ()
join waits for the thread to finish
~thread ()
~thread joins if the thread is still running
Detailed Description
The thread class is a wrapper for the std::thread, which joins in destructor and move assignment.
Definition at line 24 of file thread.h.
Constructor & Destructor Documentation
thread() [1/4]
tenacitas::concurrent::business::thread::thread (std::function< void()> && p_func) inline explicit
thread constructor
Parameters
p_func function that will run in a separated thread
Definition at line 31 of file thread.h.
References operator=(), and thread().
       : m_thread(std::move(p_func))
     {}
thread() [2/4]
tenacitas::concurrent::business::thread::thread () inline default
Referenced by thread().
thread() [3/4]
tenacitas::concurrent::business::thread::thread (const thread &) delete
thread() [4/4]
tenacitas::concurrent::business::thread::thread (thread &&) inline default noexcept
~thread()
tenacitas::concurrent::business::thread::~thread () inline
~thread joins if the thread is still running
Definition at line 64 of file thread.h.
References join().
 { join(); }
Member Function Documentation
join()
void tenacitas::concurrent::business::thread::join () inline
join waits for the thread to finish
Definition at line 54 of file thread.h.
Referenced by operator=(), and ~thread().
     {
         if (m_thread.joinable()) {
             m_thread.join();
         }
     }
operator=() [1/2]
thread& tenacitas::concurrent::business::thread::operator= (const thread &) delete
Referenced by thread().
operator=() [2/2]
thread& tenacitas::concurrent::business::thread::operator= (thread && p_th) inline noexcept
operator = move joins the 'this' thread, if the thread is still running
Parameters
p_th
Returns
Definition at line 44 of file thread.h.
References join().
     {
         join();
         m_thread = std::move(p_th.m_thread);
         return *this;
     }
The documentation for this class was generated from the following file:
/home/rodrigo/tenacitas/code/concurrent/business/thread.h