tenacitas: tenacitas::concurrent::business::thread_pool< t_data > Class Template Reference
tenacitas::concurrent::business::thread_pool< t_data > Class Template Reference
thread_pool implements a thread pool, which allows to use the producer/consumer pattern
#include <thread_pool.h>
Public Types
typedef loop_traits< t_data >::work_t work_t
work_t is the type of work function, i.e., the function that will be called in a loop in order to execute some work
Public Member Functions
thread_pool ()
thread_pool constructor
thread_pool (thread_pool &&p_pool) noexcept
move constructor
thread_pool (const thread_pool &)=delete
copy constructor not allowed
~thread_pool ()
if 'stop ' was not called, empties the pool, waiting for all the data to be processed
thread_pool & operator= (thread_pool &&p_pool) noexcept
move assignment
thread_pool & operator= (const thread_pool &)=delete
copy assignment not allowed
bool is_stopped () const
is_stopped
void add_work (uint16_t p_num_works, std::function< work_t()> p_work_factory, std::chrono::milliseconds p_work_timeout)
add_work adds a bunch of work_t functions
void add_work (work_t &&p_work, std::chrono::milliseconds p_work_timeout)
add_work adds one work_t function
void handle (const t_data &p_value)
handle sends an instance of t_data to be handled
void run ()
operator ()
void stop ()
interrupt stops the thread_pool
Detailed Description
template<typename t_data>
class tenacitas::concurrent::business::thread_pool< t_data >
thread_pool implements a thread pool, which allows to use the producer/consumer pattern
Template Parameters
t_data is the type of data inserted into the pool, so that registered work functions can "fight" among each other to get the data to process it. t_data must be default constructable, moveable and copiable
Parameters
t_data is the type of the data to be handled. If it is not void, it must be:
default constructible
move constructible
Examples:
/home/rodrigo/tenacitas/code/concurrent/test/correction/thread_pool_097/main.cpp.
Definition at line 46 of file thread_pool.h.
Member Typedef Documentation
work_t
template<typename t_data > typedef loop_traits<t_data>::work_t tenacitas::concurrent::business::thread_pool< t_data >::work_t
work_t is the type of work function, i.e., the function that will be called in a loop in order to execute some work
Definition at line 53 of file thread_pool.h.
Constructor & Destructor Documentation
thread_pool() [1/3]
template<typename t_data > tenacitas::concurrent::business::thread_pool< t_data >::thread_pool () inline
thread_pool constructor
Definition at line 56 of file thread_pool.h.
References tenacitas::logger::business::configure_cerr_log().
Referenced by tenacitas::concurrent::business::thread_pool< t_data >::thread_pool().
       : m_loops()
       , m_values()
       , m_stopped(true)
       , m_destroying(false)
     {
         // initiating the cerr_log
         tenacitas::logger::business::configure_cerr_log();
     }
thread_pool() [2/3]
template<typename t_data > tenacitas::concurrent::business::thread_pool< t_data >::thread_pool (thread_pool< t_data > && p_pool) inline noexcept
move constructor
Definition at line 67 of file thread_pool.h.
References tenacitas::concurrent::business::thread_pool< t_data >::add_work(), tenacitas::concurrent::business::thread_pool< t_data >::run(), and tenacitas::concurrent::business::thread_pool< t_data >::thread_pool().
     {
         // save if the right side was stopped
         bool _stopped = p_pool.is_stopped();
         // stop the right side
         p_pool.stop();
         // move the \p t_data collection
         m_values = std::move(p_pool.m_values);
         // build the work function collection, moving the work function from the
         // right side, and reseting the provide and break function
         for (async_loop_t& _loop_right : p_pool.m_loops) {
             async_loop_t _loop(
               std::move(_loop_right.get_work()),
               _loop_right.get_timeout(),
               [this]() -> bool { return this->stop_condition(); },
               [this]() -> std::pair<bool, t_data> { return this->data(); });
             add_work(std::move(_loop));
         }
         // seting the flags
         m_destroying = false;
         m_stopped = true;
         // if the right side was not stopped
         if (!_stopped) {
             // run this thread pool
             run();
         }
     }
thread_pool() [3/3]
template<typename t_data > tenacitas::concurrent::business::thread_pool< t_data >::thread_pool (const thread_pool< t_data > &) delete
copy constructor not allowed
~thread_pool()
template<typename t_data > tenacitas::concurrent::business::thread_pool< t_data >::~thread_pool () inline
if 'stop ' was not called, empties the pool, waiting for all the data to be processed
Definition at line 109 of file thread_pool.h.
References cerr_debug, and tenacitas::concurrent::business::thread_pool< t_data >::stop().
     {
         m_destroying = true;
         cerr_debug(this, " m_values.size() = ", m_values.size());
         if (!m_stopped) {
             while (!m_values.empty()) {
                 cerr_debug(this, " m_values.size() = ", m_values.size());
                 m_cv_data.notify_all();
                 cerr_debug(this, " waiting for poping, ", this);
                 std::unique_lock<std::mutex> _lock(m_mutex_poped);
                 m_cv_poped.wait(_lock, [this] {
                     cerr_debug(this, " poping signal arrived, ", this);
                     return true;
                 });
                 cerr_debug(this, " lock free");
             }
             cerr_debug("this, m_values.size() = ", m_values.size());
             stop();
         }
     }
Member Function Documentation
add_work() [1/2]
template<typename t_data > void tenacitas::concurrent::business::thread_pool< t_data >::add_work (uint16_t p_num_works, std::function< work_t()> p_work_factory, std::chrono::milliseconds p_work_timeout) inline
add_work adds a bunch of work_t functions
Parameters
p_num_works the number of work_t functions to be added
p_work_factory a function that creates work_t functions
p_work_timeout timeout for the work_t functions
Examples:
/home/rodrigo/tenacitas/code/concurrent/test/correction/thread_pool_097/main.cpp.
Definition at line 185 of file thread_pool.h.
Referenced by tenacitas::concurrent::business::thread_pool< t_data >::add_work(), thread_pool_097::operator()(), tenacitas::concurrent::business::thread_pool< t_data >::operator=(), tenacitas::concurrent::business::thread_pool< t_data >::stop(), tenacitas::concurrent::business::dispatcher< t_msg >::subscribe(), and tenacitas::concurrent::business::thread_pool< t_data >::thread_pool().
     {
         for (uint16_t _i = 0; _i < p_num_works; ++_i) {
             async_loop_t _loop(
               p_work_factory(),
               p_work_timeout,
               [this]() -> bool { return this->stop_condition(); },
               [this]() -> std::pair<bool, t_data> { return this->data(); });
             add_work(std::move(_loop));
         }
     }
add_work() [2/2]
template<typename t_data > void tenacitas::concurrent::business::thread_pool< t_data >::add_work (work_t && p_work, std::chrono::milliseconds p_work_timeout) inline
add_work adds one work_t function
Parameters
p_work the work_t fuction to be added
p_work_timeout timeout of this work_t function
Definition at line 205 of file thread_pool.h.
References tenacitas::concurrent::business::thread_pool< t_data >::add_work().
     {
         async_loop_t _loop(
           std::move(p_work),
           p_work_timeout,
           [this]() -> bool { return this->stop_condition(); },
           [this]() -> std::pair<bool, t_data> { return this->data(); });
         add_work(std::move(_loop));
     }
handle()
template<typename t_data > void tenacitas::concurrent::business::thread_pool< t_data >::handle (const t_data & p_value) inline
handle sends an instance of t_data to be handled
Parameters
p_value the value to be handled
Examples:
/home/rodrigo/tenacitas/code/concurrent/test/correction/thread_pool_097/main.cpp.
Definition at line 220 of file thread_pool.h.
Referenced by thread_pool_097::operator()().
 { add_data(p_value); }
is_stopped()
template<typename t_data > bool tenacitas::concurrent::business::thread_pool< t_data >::is_stopped () const inline
is_stopped
Returns
true if the loop is not running; false othewise
Definition at line 177 of file thread_pool.h.
Referenced by tenacitas::concurrent::business::thread_pool< t_data >::operator=().
 { return m_stopped; }
operator=() [1/2]
template<typename t_data > thread_pool& tenacitas::concurrent::business::thread_pool< t_data >::operator= (thread_pool< t_data > && p_pool) inline noexcept
move assignment
Definition at line 132 of file thread_pool.h.
References tenacitas::concurrent::business::thread_pool< t_data >::add_work(), tenacitas::concurrent::business::thread_pool< t_data >::is_stopped(), and tenacitas::concurrent::business::thread_pool< t_data >::run().
     {
         if (this != &p_pool) {
             // save if the right side was stopped
             bool _stopped = p_pool.is_stopped();
             // stop the right side
             p_pool.stop();
             // move the \p t_data collection
             m_values = std::move(p_pool.m_values);
             // build the work function collection, moving the work function from
             // the right side, and reseting the provide and break function
             for (async_loop_t& _loop_right : p_pool.m_loops) {
                 async_loop_t _loop(
                   std::move(_loop_right.get_work()),
                   _loop_right.get_timeout(),
                   [this]() -> bool { return this->stop_condition(); },
                   [this]() -> std::pair<bool, t_data> { return this->data(); });
                 add_work(std::move(_loop));
             }
             // seting the flags
             m_destroying = false;
             m_stopped = true;
             // if the right side was not stopped
             if (!_stopped) {
                 // run this thread pool
                 run();
             }
         }
         return *this;
     }
operator=() [2/2]
template<typename t_data > thread_pool& tenacitas::concurrent::business::thread_pool< t_data >::operator= (const thread_pool< t_data > &) delete
copy assignment not allowed
run()
template<typename t_data > void tenacitas::concurrent::business::thread_pool< t_data >::run () inline
operator ()
run starts the thread_pool
From this call on, the work_t functions will to "fight" among each other, in order to process any instance of t_data that was inserted, using the handle method, into the pool
Examples:
/home/rodrigo/tenacitas/code/concurrent/test/correction/thread_pool_097/main.cpp.
Definition at line 233 of file thread_pool.h.
Referenced by thread_pool_097::operator()(), tenacitas::concurrent::business::thread_pool< t_data >::operator=(), tenacitas::concurrent::business::dispatcher< t_msg >::subscribe(), and tenacitas::concurrent::business::thread_pool< t_data >::thread_pool().
     {
         if (m_stopped) {
             run_common();
         }
     }
stop()
template<typename t_data > void tenacitas::concurrent::business::thread_pool< t_data >::stop () inline
interrupt stops the thread_pool
From this call on, the work_t functions will stop "fighting" among each other, in order to process any instance of t_data that was inserted, using the handle method, into the pool
Definition at line 247 of file thread_pool.h.
References tenacitas::concurrent::business::thread_pool< t_data >::add_work(), and cerr_debug.
Referenced by tenacitas::concurrent::business::thread_pool< t_data >::~thread_pool().
     {
         std::unique_lock<std::mutex> _lock(m_mutex_stop);
         m_stopped = true;
         if (m_loops.empty()) {
             return;
         }
         m_cv_data.notify_all();
         for (async_loop_t& _loop : m_loops) {
             cerr_debug("stopping loop ", &_loop);
             _loop.stop();
         }
     }
The documentation for this class was generated from the following file:
/home/rodrigo/tenacitas/code/concurrent/business/thread_pool.h