tenacitas: tenacitas::logger::business Namespace Reference
tenacitas::logger::business Namespace Reference
namespace of the class group
Functions
void configure_cerr_log ()
configure_cerr_log configures logging to cerr
void configure_cout_log ()
configure_cout_log configures logging to cout
void configure_file_log (const std::string &p_path=".", const std::string &p_base_name="log", uint32_t p_max_file_size=10 *1024 *1024, std::chrono::minutes p_retention=std::chrono::minutes(2 *24 *60), const std::string &p_closed_extension="closed")
configure_file_log configures logging in file
Detailed Description
namespace of the class group
Function Documentation
configure_cerr_log()
void tenacitas::logger::business::configure_cerr_log ()
configure_cerr_log configures logging to cerr
This namespace function must be called only one time to configure logging to cerr
There are 6 log levels, from the lowest: 'test', 'debug', 'info', 'warn', 'error' and 'fatal'. The log level starts in 'error', so only 'error' and 'fatal' messages will be logged.
If one wants to change the log level, the 'cerr_set_test', 'cerr_set_debug', 'cerr_set_info' or 'cerr_set_warn' macro command must be called
A log line has this format: log-level|timestamp-millisecs|thread-id|file|line|user-contents For example: T|1552098707355|140299908863808|thread_pool_tester.h|59|adding (0000000005,012345678901234567890123456789,1552098707355)
Examples:
/home/rodrigo/tenacitas/code/logger/test/correction/cerr_log_single/main.cpp, and /home/rodrigo/tenacitas/code/logger/test/correction/cout_log_multi/main.cpp.
Referenced by cerr_log_single::operator()(), cerr_log_multi::operator()(), tenacitas::concurrent::business::dispatcher< t_msg >::subscribe(), and tenacitas::concurrent::business::thread_pool< t_data >::thread_pool().
configure_cout_log()
void tenacitas::logger::business::configure_cout_log ()
configure_cout_log configures logging to cout
This namespace function must be called only one time to configure logging to cout
There are 6 log levels, from the lowest: 'test', 'debug', 'info', 'warn', 'error' and 'fatal'. The log level starts in 'error', so only 'error' and 'fatal' messages will be logged.
If one wants to change the log level, the 'cout_set_test', 'cout_set_debug', 'cout_set_info' or 'cout_set_warn' must be called
A log line has this format: log-level|timestamp-millisecs|thread-id|file|line|user-contents
For T|1552098707355|140299908863808|thread_pool_tester.h|59|adding (0000000005,012345678901234567890123456789,1552098707355)
configure_file_log()
void tenacitas::logger::business::configure_file_log (const std::string & p_path = ".", const std::string & p_base_name = "log", uint32_t p_max_file_size = 10 *1024 *1024, std::chrono::minutes p_retention = std::chrono::minutes(2 *24 *60), const std::string & p_closed_extension = "closed")
configure_file_log configures logging in file
This namespace function must be called only one time to configure logging to a file
Parameters
p_path path is where the log files will be generated
p_base_name first string in the log file name; one can use, for example, the name of the program
p_max_file_size maximum size of the file, in bytes
p_retention amount of time that the file will exist, before being deleted, in minutes
p_closed_extension is a string that will be appended to the file name, showing that it was closed, because it has reached its maximum size, or the program has finished.
Using the default values, log files will be created at the current path; the name of the files will begin with 'log'; when it reaches 10MB a new log file will be created; each log file will last up to 2 days
A log file name is the combination of 'p_base_name' concatenated with the process id (PID), and with the amount of milliseconds of when the file was created, like: 'log_0000008165_1545843474201246.log'.
When this files reaches (almost) 10MB, it will be renamed to 'log_0000008165_1545843474201246.log.closed'.
When it is more that 2 days old, it will be deleted.
There are 6 log levels, from the lowest: 'test', 'debug', 'info', 'warn', 'error' and 'fatal'. The log level starts in 'error', so only 'error' and 'fatal' messages will be logged.
If one wants to change the log level, the 'file_set_test', 'file_set_debug', 'file_set_info' or 'file_set_warn' must be called
A log line has this format: log-level|timestamp-millisecs|thread-id|file|line|user-contents
For example T|1552098707355|140299908863808|thread_pool_tester.h|59|adding (0000000005,012345678901234567890123456789,1552098707355)
Examples:
/home/rodrigo/tenacitas/code/logger/test/correction/file_log_single/main.cpp.
Referenced by file_log_single::operator()().