tenacitas: thread_pool_097 Struct Reference
thread_pool_097 Struct Reference
Public Member Functions
bool operator() ()
Detailed Description
Examples:
/home/rodrigo/tenacitas/code/concurrent/test/correction/thread_pool_097/main.cpp.
Definition at line 37 of file main.cpp.
Member Function Documentation
operator()()
bool thread_pool_097::operator() () inline
Definition at line 39 of file main.cpp.
References tenacitas::concurrent::business::thread_pool< t_data >::add_work(), cerr_test, work_1::counter, work_2::counter, tenacitas::concurrent::business::thread_pool< t_data >::handle(), and tenacitas::concurrent::business::thread_pool< t_data >::run().
     {
         work_1 _work_1;
         work_2 _work_2;
         {
             thread_pool_t _pool;
             int32_t _value = 0;
             int16_t _counter = 0;
             sleeping_loop_t _loop(std::chrono::milliseconds(100),
                                   [&_pool, &_value, &_counter]() -> bool {
                                       ++_value;
                                       ++_counter;
                                       _pool.handle(_value);
                                       return true;
                                   },
                                   std::chrono::milliseconds(300));
             _pool.add_work(
               [&_work_1](int32_t&& p_val) -> bool {
                   return _work_1(std::move(p_val));
               },
               std::chrono::milliseconds(200));
             _pool.add_work(
               [&_work_2](int32_t&& p_val) -> bool {
                   return _work_2(std::move(p_val));
               },
               std::chrono::milliseconds(200));
             _loop.run();
             std::this_thread::sleep_for(std::chrono::seconds(6));
             _loop.stop();
             cerr_test("counter = ", _counter);
             _pool.run();
         }
         cerr_test("work 1 counter = ", _work_1.counter);
         cerr_test("work 2 counter = ", _work_2.counter);
         return ((_work_1.counter + _work_2.counter) == 60);
     }
The documentation for this struct was generated from the following file:
/home/rodrigo/tenacitas/code/concurrent/test/correction/thread_pool_097/main.cpp