@startuml

hide empty members
skinparam processorsInheritance 2
skinparam linetype ortho


class mat_t<t_data> {    
    add(t_data)
    get() : t_data
}

class mat_ptr

class circular_fixed_size_mat_t<t_data>
class circular_unlimited_size_mat_t<t_data>
class linear_size_mat_t<t_data>

class size

class worker_t<t_data> {
    + operator()(t_data) 
}

class id


class processor_t<t_data> {
    + add(worker_t)
    + add(worker_t, timeout)
    + set(mat_ptr)
    + operator()(t_data)    
}

class processors_t <t_data> <<static>> {
    + add_processor(processor_t.id, mat_ptr, size)
    + add_competitor(processor_t.id, worker_t, timeout)
    + handle(t_data)
}

class subscriber_t  <t_data>  <<function>> {
    + add_processor(processor_t.id, mat_ptr, size)
    + add_competitor(processor_t.id, worker_t, timeout)
}

class publisher_t  <t_data> <<function>> {
    + operator()(t_data)
}

mat_t +-up- mat_ptr
mat_t <|-- circular_fixed_size_mat_t
mat_t <|-- circular_unlimited_size_mat_t
mat_t <|-- linear_size_mat_t


processor_t +-- id
processor_t *-right- id

mat_t *-up- size
mat_t *-- "*" t_data
worker_t ..> "<<parameter>>" t_data
processor_t *-- mat_ptr
processor_t *-- "*" worker_t

processors_t *-- "*" processor_t

subscriber_t ..> "<<use>>" processors_t
publisher_t ..> "<<use>>" processors_t



@enduml