@startuml

hide empty members
skinparam workersInheritance 2
skinparam linetype ortho


class data 

class queue {    
    add(data)
    get() : data
}

class size

class competitor {
    + operator()(data) 
}

class id


class worker {
    + add(competitor)
    + add(competitor, timeout)
    + operator()(data)    
}

class workers <<static>> {
    + add_worker(worker.id, queue, size)
    + add_competitor(worker.id, competitor, timeout)
    + handle(data)
}

class subscriber <<function>>
class publisher <<function>>

class subscriber {
    + add_worker(worker.id, queue, size)
    + add_competitor(worker.id, competitor, timeout)
}

class publisher {
    + operator()(data)
}

worker +-- id
worker *-right- id

queue *-- size
queue *-- "*" data
competitor ..> "<<parameter>>" data
worker *-- queue
worker *-- "*" competitor

workers *-- "*" worker

subscriber ..> "<<use>>" workers
publisher ..> "<<use>>" workers



@enduml