@startuml

hide empty members

skinparam groupInheritance 2

n_params  <|-- n_params_ret
n_params  <|-- n_params_no_ret

one_param  <|-- one_param_ret
one_param  <|-- one_param_no_ret

no_param  <|-- no_param_ret
no_param  <|-- no_param_no_ret

executer <|-- n_params
executer <|-- one_param
executer <|-- no_param


@enduml