@startuml

hide empty description

[*] --> waiting_for_work : create
waiting_for_work --> waiting_for_work : start (002)
waiting_for_work --> working : work (004)
working --> working : start (003)
waiting_for_work --> stopped : stop (000)
stopped --> stopped : stop (001)
working --> waiting_for_work : timeout (005)
working --> stopped : stop (006)
working --> waiting_for_work : done (007)
waiting_for_work --> waiting_for_work : return (008)
@enduml