@startuml

hide empty members
allow_mixing

class type
class types
class lexeme
class symbol
class symbols
class recognizer
class scanner {
    + scanner(std::string::const_iterator p_begin, std::string::const_iterator p_end)
    + symbol operator()()
}
type *-- recognizer

types +--types.const_iterator


symbol *-- lexeme 
symbol *--  "m_ptr" type

symbols *-- "*" symbol

types *-- "*" type 

class  tokens <<(T,#BBCCDD) type>>
class  reserved_words <<(T,#BBCCDD) type>>
class  identifier <<(T,#BBCCDD) type>>

@enduml