@startuml

hide empty members
hide circle
allow_mixing

namespace std {
    class set<t>
    class string
    class function <t>
}

class scanner {
    + scanner(std::string::const_iterator p_begin, std::string::const_iterator p_end)
    + symbol operator()()
}
class symbol
class lexeme
class value_recognizer {
    + type operator()(const std.string &)
}

class value_recognizers
class type {
    + {static} unrecognized
}
class types <<static>>
class "std.set<std.string>" as string_set

class pattern_recognizers
class pattern_recognizer {
    + type operator()(const std.string &)
}

pattern_recognizers *-- pattern_recognizer

pattern_recognizer *-- type

types *-- type

value_recognizer *-- "m_size" uint8_t
value_recognizer *--  type
value_recognizer *-- string_set
value_recognizers *-- "*" value_recognizer

symbol *-- lexeme
symbol *-- type

scanner *-- types
scanner *-- value_recognizers
scanner *-- pattern_recognizers

@enduml