@startuml

hide empty members
allow_mixing

class scanner {
    + scanner(std::string::const_iterator p_begin, std::string::const_iterator p_end)
    + symbol operator()()
}
class symbol
class lexeme
class type_ptr <<(T,#BBCCDD) type *>>
class token <<(T,#BBCCDD) type>>
class tokens

type *-- recognizer

tokens *-- "*" type

types *-- "*" type

symbol *-- lexeme
symbol *-- type_ptr

scanner *-- types
scanner *-- tokens


@enduml