@startuml
hide circle
hide empty members
allow_mixing
skinparam linetype ortho
'left to right direction

A ||..|{ B
B ||..|{ BC
C ||..|{ BC
C ||..|| D
C ||..|{ C
A ||..|{ E
H ||..|{ E
E ||..|{ F
G ||..|{ BC
@enduml