@startuml

hide empty members
allow_mixing
left to right direction

class Employee {
+ id : autoincrement
+ name : varchar[100]
+ birthday : date 
}

class Project {
+ id : autoincrement 
+ name : varchar[100]
}

class Dependent {
+ id : autoincrement
+ name : varchar[100]
+ birthday : date
}

Employee o-- "*" Project
Project o-- "*" Employee
Employee *-- "*" Dependent
Employee "0..1 boss" o-- "0..*" Employee

@enduml